// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/bidon-io/bidon-backend/internal/bidding/adapters"
	"github.com/bidon-io/bidon-backend/internal/sdkapi"
	"github.com/bidon-io/bidon-backend/internal/sdkapi/schema"
	"sync"
)

// Ensure, that LossNotificationHandlerMock does implement sdkapi.LossNotificationHandler.
// If this is not the case, regenerate this file with moq.
var _ sdkapi.LossNotificationHandler = &LossNotificationHandlerMock{}

// LossNotificationHandlerMock is a mock implementation of sdkapi.LossNotificationHandler.
//
//	func TestSomethingThatUsesLossNotificationHandler(t *testing.T) {
//
//		// make and configure a mocked sdkapi.LossNotificationHandler
//		mockedLossNotificationHandler := &LossNotificationHandlerMock{
//			HandleLossFunc: func(contextMoqParam context.Context, imp *schema.Imp, demandResponses []*adapters.DemandResponse) error {
//				panic("mock out the HandleLoss method")
//			},
//		}
//
//		// use mockedLossNotificationHandler in code that requires sdkapi.LossNotificationHandler
//		// and then make assertions.
//
//	}
type LossNotificationHandlerMock struct {
	// HandleLossFunc mocks the HandleLoss method.
	HandleLossFunc func(contextMoqParam context.Context, imp *schema.Imp, demandResponses []*adapters.DemandResponse) error

	// calls tracks calls to the methods.
	calls struct {
		// HandleLoss holds details about calls to the HandleLoss method.
		HandleLoss []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// Imp is the imp argument value.
			Imp *schema.Imp
			// DemandResponses is the demandResponses argument value.
			DemandResponses []*adapters.DemandResponse
		}
	}
	lockHandleLoss sync.RWMutex
}

// HandleLoss calls HandleLossFunc.
func (mock *LossNotificationHandlerMock) HandleLoss(contextMoqParam context.Context, imp *schema.Imp, demandResponses []*adapters.DemandResponse) error {
	if mock.HandleLossFunc == nil {
		panic("LossNotificationHandlerMock.HandleLossFunc: method is nil but LossNotificationHandler.HandleLoss was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		Imp             *schema.Imp
		DemandResponses []*adapters.DemandResponse
	}{
		ContextMoqParam: contextMoqParam,
		Imp:             imp,
		DemandResponses: demandResponses,
	}
	mock.lockHandleLoss.Lock()
	mock.calls.HandleLoss = append(mock.calls.HandleLoss, callInfo)
	mock.lockHandleLoss.Unlock()
	return mock.HandleLossFunc(contextMoqParam, imp, demandResponses)
}

// HandleLossCalls gets all the calls that were made to HandleLoss.
// Check the length with:
//
//	len(mockedLossNotificationHandler.HandleLossCalls())
func (mock *LossNotificationHandlerMock) HandleLossCalls() []struct {
	ContextMoqParam context.Context
	Imp             *schema.Imp
	DemandResponses []*adapters.DemandResponse
} {
	var calls []struct {
		ContextMoqParam context.Context
		Imp             *schema.Imp
		DemandResponses []*adapters.DemandResponse
	}
	mock.lockHandleLoss.RLock()
	calls = mock.calls.HandleLoss
	mock.lockHandleLoss.RUnlock()
	return calls
}
