// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/bidon-io/bidon-backend/internal/auction"
	"github.com/bidon-io/bidon-backend/internal/sdkapi"
	"github.com/bidon-io/bidon-backend/internal/sdkapi/schema"
	"sync"
)

// Ensure, that StatsNotificationHandlerMock does implement sdkapi.StatsNotificationHandler.
// If this is not the case, regenerate this file with moq.
var _ sdkapi.StatsNotificationHandler = &StatsNotificationHandlerMock{}

// StatsNotificationHandlerMock is a mock implementation of sdkapi.StatsNotificationHandler.
//
//	func TestSomethingThatUsesStatsNotificationHandler(t *testing.T) {
//
//		// make and configure a mocked sdkapi.StatsNotificationHandler
//		mockedStatsNotificationHandler := &StatsNotificationHandlerMock{
//			HandleStatsFunc: func(contextMoqParam context.Context, stats schema.Stats, config *auction.Config)  {
//				panic("mock out the HandleStats method")
//			},
//		}
//
//		// use mockedStatsNotificationHandler in code that requires sdkapi.StatsNotificationHandler
//		// and then make assertions.
//
//	}
type StatsNotificationHandlerMock struct {
	// HandleStatsFunc mocks the HandleStats method.
	HandleStatsFunc func(contextMoqParam context.Context, stats schema.Stats, config *auction.Config)

	// calls tracks calls to the methods.
	calls struct {
		// HandleStats holds details about calls to the HandleStats method.
		HandleStats []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// Stats is the stats argument value.
			Stats schema.Stats
			// Config is the config argument value.
			Config *auction.Config
		}
	}
	lockHandleStats sync.RWMutex
}

// HandleStats calls HandleStatsFunc.
func (mock *StatsNotificationHandlerMock) HandleStats(contextMoqParam context.Context, stats schema.Stats, config *auction.Config) {
	if mock.HandleStatsFunc == nil {
		panic("StatsNotificationHandlerMock.HandleStatsFunc: method is nil but StatsNotificationHandler.HandleStats was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		Stats           schema.Stats
		Config          *auction.Config
	}{
		ContextMoqParam: contextMoqParam,
		Stats:           stats,
		Config:          config,
	}
	mock.lockHandleStats.Lock()
	mock.calls.HandleStats = append(mock.calls.HandleStats, callInfo)
	mock.lockHandleStats.Unlock()
	mock.HandleStatsFunc(contextMoqParam, stats, config)
}

// HandleStatsCalls gets all the calls that were made to HandleStats.
// Check the length with:
//
//	len(mockedStatsNotificationHandler.HandleStatsCalls())
func (mock *StatsNotificationHandlerMock) HandleStatsCalls() []struct {
	ContextMoqParam context.Context
	Stats           schema.Stats
	Config          *auction.Config
} {
	var calls []struct {
		ContextMoqParam context.Context
		Stats           schema.Stats
		Config          *auction.Config
	}
	mock.lockHandleStats.RLock()
	calls = mock.calls.HandleStats
	mock.lockHandleStats.RUnlock()
	return calls
}
