export const DEMAND_SOURCE_OPTIONS = [
  { label: "Admob", value: "DemandSourceAccount::Admob" },
  { label: "Amazon", value: "DemandSourceAccount::Amazon" },
  { label: "Applovin", value: "DemandSourceAccount::Applovin" },
  { label: "Bidmachine", value: "DemandSourceAccount::BidMachine" },
  { label: "BigoAds", value: "DemandSourceAccount::BigoAds" },
  { label: "Chartboost", value: "DemandSourceAccount::Chartboost" },
  { label: "DTExchange", value: "DemandSourceAccount::DtExchange" },
  { label: "Google Ad Manager", value: "DemandSourceAccount::GAM" },
  { label: "Inmobi", value: "DemandSourceAccount::Inmobi" },
  { label: "IronSource", value: "DemandSourceAccount::IronSource" },
  { label: "Meta", value: "DemandSourceAccount::Meta" },
  { label: "Mintegral", value: "DemandSourceAccount::Mintegral" },
  { label: "MobileFuse", value: "DemandSourceAccount::MobileFuse" },
  { label: "Moloco", value: "DemandSourceAccount::Moloco" },
  { label: "Start.io", value: "DemandSourceAccount::StartIO" },
  { label: "TaurusX", value: "DemandSourceAccount::TaurusX" },
  { label: "UnityAds", value: "DemandSourceAccount::UnityAds" },
  { label: "Vungle", value: "DemandSourceAccount::Vungle" },
  { label: "VKAds", value: "DemandSourceAccount::VKAds" },
  { label: "Yandex", value: "DemandSourceAccount::Yandex" },
];
