version: "2"
linters:
  default: none
  enable:
    - errcheck
    - fatcontext
    - govet
    - ineffassign
    - loggercheck
    - mirror
    - revive
    - staticcheck
    - thelper
    - usestdlibvars
  settings:
    staticcheck:
      checks:
        - -SA1019
        - -SA5008
        - all
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/bidon-io/bidon-backend)
    goimports:
      local-prefixes:
        - github.com/bidon-io/bidon-backend
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
