name: bidon-go

services:
  postgres:
    image: postgres:alpine
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=bidon
    volumes:
      - pgdata:/var/lib/postgresql/data

  postgres-test:
    image: postgres:alpine
    profiles: [test]
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=bidon
    volumes:
      - pgdata-test:/var/lib/postgresql/data

volumes:
  pgdata:
  pgdata-test:
