// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for GetAuctionParamsAdType.
const (
	GetAuctionParamsAdTypeBanner       GetAuctionParamsAdType = "banner"
	GetAuctionParamsAdTypeInterstitial GetAuctionParamsAdType = "interstitial"
	GetAuctionParamsAdTypeRewarded     GetAuctionParamsAdType = "rewarded"
)

// Defines values for GetAuctionJSONBodyAdObjectBannerFormat.
const (
	GetAuctionJSONBodyAdObjectBannerFormatADAPTIVE    GetAuctionJSONBodyAdObjectBannerFormat = "ADAPTIVE"
	GetAuctionJSONBodyAdObjectBannerFormatBANNER      GetAuctionJSONBodyAdObjectBannerFormat = "BANNER"
	GetAuctionJSONBodyAdObjectBannerFormatLEADERBOARD GetAuctionJSONBodyAdObjectBannerFormat = "LEADERBOARD"
	GetAuctionJSONBodyAdObjectBannerFormatMREC        GetAuctionJSONBodyAdObjectBannerFormat = "MREC"
)

// Defines values for GetAuctionJSONBodyAdObjectOrientation.
const (
	LANDSCAPE GetAuctionJSONBodyAdObjectOrientation = "LANDSCAPE"
	PORTRAIT  GetAuctionJSONBodyAdObjectOrientation = "PORTRAIT"
)

// Defines values for GetAuctionJSONBodyDeviceConnectionType.
const (
	GetAuctionJSONBodyDeviceConnectionTypeCELLULAR        GetAuctionJSONBodyDeviceConnectionType = "CELLULAR"
	GetAuctionJSONBodyDeviceConnectionTypeCELLULAR2G      GetAuctionJSONBodyDeviceConnectionType = "CELLULAR_2_G"
	GetAuctionJSONBodyDeviceConnectionTypeCELLULAR3G      GetAuctionJSONBodyDeviceConnectionType = "CELLULAR_3_G"
	GetAuctionJSONBodyDeviceConnectionTypeCELLULAR4G      GetAuctionJSONBodyDeviceConnectionType = "CELLULAR_4_G"
	GetAuctionJSONBodyDeviceConnectionTypeCELLULAR5G      GetAuctionJSONBodyDeviceConnectionType = "CELLULAR_5_G"
	GetAuctionJSONBodyDeviceConnectionTypeCELLULARUNKNOWN GetAuctionJSONBodyDeviceConnectionType = "CELLULAR_UNKNOWN"
	GetAuctionJSONBodyDeviceConnectionTypeETHERNET        GetAuctionJSONBodyDeviceConnectionType = "ETHERNET"
	GetAuctionJSONBodyDeviceConnectionTypeWIFI            GetAuctionJSONBodyDeviceConnectionType = "WIFI"
)

// Defines values for GetAuctionJSONBodyDeviceType.
const (
	GetAuctionJSONBodyDeviceTypePHONE  GetAuctionJSONBodyDeviceType = "PHONE"
	GetAuctionJSONBodyDeviceTypeTABLET GetAuctionJSONBodyDeviceType = "TABLET"
)

// Defines values for GetConfigJSONBodyDeviceConnectionType.
const (
	GetConfigJSONBodyDeviceConnectionTypeCELLULAR        GetConfigJSONBodyDeviceConnectionType = "CELLULAR"
	GetConfigJSONBodyDeviceConnectionTypeCELLULAR2G      GetConfigJSONBodyDeviceConnectionType = "CELLULAR_2_G"
	GetConfigJSONBodyDeviceConnectionTypeCELLULAR3G      GetConfigJSONBodyDeviceConnectionType = "CELLULAR_3_G"
	GetConfigJSONBodyDeviceConnectionTypeCELLULAR4G      GetConfigJSONBodyDeviceConnectionType = "CELLULAR_4_G"
	GetConfigJSONBodyDeviceConnectionTypeCELLULAR5G      GetConfigJSONBodyDeviceConnectionType = "CELLULAR_5_G"
	GetConfigJSONBodyDeviceConnectionTypeCELLULARUNKNOWN GetConfigJSONBodyDeviceConnectionType = "CELLULAR_UNKNOWN"
	GetConfigJSONBodyDeviceConnectionTypeETHERNET        GetConfigJSONBodyDeviceConnectionType = "ETHERNET"
	GetConfigJSONBodyDeviceConnectionTypeWIFI            GetConfigJSONBodyDeviceConnectionType = "WIFI"
)

// Defines values for GetConfigJSONBodyDeviceType.
const (
	GetConfigJSONBodyDeviceTypePHONE  GetConfigJSONBodyDeviceType = "PHONE"
	GetConfigJSONBodyDeviceTypeTABLET GetConfigJSONBodyDeviceType = "TABLET"
)

// Defines values for PostStatsParamsAdType.
const (
	PostStatsParamsAdTypeBanner       PostStatsParamsAdType = "banner"
	PostStatsParamsAdTypeInterstitial PostStatsParamsAdType = "interstitial"
	PostStatsParamsAdTypeRewarded     PostStatsParamsAdType = "rewarded"
)

// Defines values for PostStatsJSONBodyDeviceConnectionType.
const (
	CELLULAR        PostStatsJSONBodyDeviceConnectionType = "CELLULAR"
	CELLULAR2G      PostStatsJSONBodyDeviceConnectionType = "CELLULAR_2_G"
	CELLULAR3G      PostStatsJSONBodyDeviceConnectionType = "CELLULAR_3_G"
	CELLULAR4G      PostStatsJSONBodyDeviceConnectionType = "CELLULAR_4_G"
	CELLULAR5G      PostStatsJSONBodyDeviceConnectionType = "CELLULAR_5_G"
	CELLULARUNKNOWN PostStatsJSONBodyDeviceConnectionType = "CELLULAR_UNKNOWN"
	ETHERNET        PostStatsJSONBodyDeviceConnectionType = "ETHERNET"
	WIFI            PostStatsJSONBodyDeviceConnectionType = "WIFI"
)

// Defines values for PostStatsJSONBodyDeviceType.
const (
	PHONE  PostStatsJSONBodyDeviceType = "PHONE"
	TABLET PostStatsJSONBodyDeviceType = "TABLET"
)

// Defines values for PostStatsJSONBodyStatsAdUnitsStatus.
const (
	PostStatsJSONBodyStatsAdUnitsStatusEmpty   PostStatsJSONBodyStatsAdUnitsStatus = ""
	PostStatsJSONBodyStatsAdUnitsStatusFAIL    PostStatsJSONBodyStatsAdUnitsStatus = "FAIL"
	PostStatsJSONBodyStatsAdUnitsStatusPENDING PostStatsJSONBodyStatsAdUnitsStatus = "PENDING"
	PostStatsJSONBodyStatsAdUnitsStatusSUCCESS PostStatsJSONBodyStatsAdUnitsStatus = "SUCCESS"
)

// Defines values for PostStatsJSONBodyStatsResultBannerFormat.
const (
	PostStatsJSONBodyStatsResultBannerFormatADAPTIVE    PostStatsJSONBodyStatsResultBannerFormat = "ADAPTIVE"
	PostStatsJSONBodyStatsResultBannerFormatBANNER      PostStatsJSONBodyStatsResultBannerFormat = "BANNER"
	PostStatsJSONBodyStatsResultBannerFormatLEADERBOARD PostStatsJSONBodyStatsResultBannerFormat = "LEADERBOARD"
	PostStatsJSONBodyStatsResultBannerFormatMREC        PostStatsJSONBodyStatsResultBannerFormat = "MREC"
)

// Defines values for PostStatsJSONBodyStatsResultBidType.
const (
	CPM PostStatsJSONBodyStatsResultBidType = "CPM"
	RTB PostStatsJSONBodyStatsResultBidType = "RTB"
)

// Defines values for PostStatsJSONBodyStatsResultStatus.
const (
	PostStatsJSONBodyStatsResultStatusAUCTIONCANCELLED PostStatsJSONBodyStatsResultStatus = "AUCTION_CANCELLED"
	PostStatsJSONBodyStatsResultStatusFAIL             PostStatsJSONBodyStatsResultStatus = "FAIL"
	PostStatsJSONBodyStatsResultStatusSUCCESS          PostStatsJSONBodyStatsResultStatus = "SUCCESS"
)

// GetAuctionJSONBody defines parameters for GetAuction.
type GetAuctionJSONBody struct {
	AdObject struct {
		// AuctionConfigurationId ID of the auction configuration
		AuctionConfigurationId *int64 `json:"auction_configuration_id,omitempty"`

		// AuctionConfigurationUid UID of the auction configuration
		AuctionConfigurationUid *string `json:"auction_configuration_uid,omitempty"`

		// AuctionId Unique identifier for the auction
		AuctionId *string `json:"auction_id,omitempty"`

		// AuctionKey Generated key for the auction request
		AuctionKey *string `json:"auction_key,omitempty"`

		// AuctionPricefloor PriceFloor for the auction
		AuctionPricefloor float32 `json:"auction_pricefloor"`
		Banner            *struct {
			// Format Format of the banner ad
			Format GetAuctionJSONBodyAdObjectBannerFormat `json:"format"`
		} `json:"banner,omitempty"`

		// Demands Map of demands
		Demands map[string]map[string]interface{} `json:"demands"`

		// Interstitial Empty schema for interstitial ad configuration
		Interstitial *map[string]interface{} `json:"interstitial,omitempty"`

		// Orientation Orientation of the ad
		Orientation *GetAuctionJSONBodyAdObjectOrientation `json:"orientation,omitempty"`

		// Rewarded Empty schema for rewarded ad configuration
		Rewarded *map[string]interface{} `json:"rewarded,omitempty"`
	} `json:"ad_object"`
	Adapters map[string]struct {
		SdkVersion string `json:"sdk_version"`
		Version    string `json:"version"`
	} `json:"adapters"`
	App struct {
		// Bundle The bundle identifier of the application, typically in reverse domain name notation (e.g., com.example.myapp).
		Bundle string `json:"bundle"`

		// Framework The name of the framework used by the application (e.g., React Native, Flutter, etc.).
		Framework string `json:"framework"`

		// FrameworkVersion The version of the framework used by the application, specifying compatibility.
		FrameworkVersion *string `json:"framework_version,omitempty"`

		// Key A unique key or identifier for the application.
		Key string `json:"key"`

		// PluginVersion The version of the plugin integrated into the application
		PluginVersion *string `json:"plugin_version,omitempty"`

		// SdkVersion The version of the SDK used in the application.
		SdkVersion *string `json:"sdk_version,omitempty"`

		// Skadn An array of SKAdNetwork IDs for ad attribution, used primarily for iOS applications.
		Skadn *[]string `json:"skadn,omitempty"`

		// Version The version of the application, typically following semantic versioning (e.g., 1.0.0).
		Version string `json:"version"`
	} `json:"app"`
	Device struct {
		// Carrier Carrier
		Carrier *string `json:"carrier,omitempty"`

		// ConnectionType Connection Type
		ConnectionType GetAuctionJSONBodyDeviceConnectionType `json:"connection_type"`
		Geo            *struct {
			// Accuracy Accuracy of the location data
			Accuracy *float32 `json:"accuracy,omitempty"`

			// City City name
			City *string `json:"city,omitempty"`

			// Country Country code or name
			Country *string `json:"country,omitempty"`

			// Lastfix Timestamp of the last location fix in seconds since epoch
			Lastfix *int `json:"lastfix,omitempty"`

			// Lat Latitude of the location
			Lat *float32 `json:"lat,omitempty"`

			// Lon Longitude of the location
			Lon *float32 `json:"lon,omitempty"`

			// Utcoffset UTC offset in minutes
			Utcoffset *int `json:"utcoffset,omitempty"`

			// Zip ZIP or postal code
			Zip *string `json:"zip,omitempty"`
		} `json:"geo,omitempty"`

		// H Height
		H int `json:"h"`

		// Hwv Hardware Version
		Hwv string `json:"hwv"`

		// Js JavaScript support
		Js int `json:"js"`

		// Language Language
		Language string `json:"language"`

		// Make Manufacturer
		Make string `json:"make"`

		// Mccmnc Mobile Country Code and Mobile Network Code
		Mccmnc *string `json:"mccmnc,omitempty"`

		// Model Model
		Model string `json:"model"`

		// Os Operating System
		Os string `json:"os"`

		// Osv Operating System Version
		Osv string `json:"osv"`

		// Ppi Pixels per Inch (PPI)
		Ppi int `json:"ppi"`

		// Pxratio Pixel Ratio
		Pxratio float32 `json:"pxratio"`

		// Type Device Type
		Type *GetAuctionJSONBodyDeviceType `json:"type,omitempty"`

		// Ua UserAgent
		Ua string `json:"ua"`

		// W Width
		W int `json:"w"`
	} `json:"device"`
	Ext *string `json:"ext,omitempty"`
	Geo *struct {
		// Accuracy Accuracy of the location data
		Accuracy *float32 `json:"accuracy,omitempty"`

		// City City name
		City *string `json:"city,omitempty"`

		// Country Country code or name
		Country *string `json:"country,omitempty"`

		// Lastfix Timestamp of the last location fix in seconds since epoch
		Lastfix *int `json:"lastfix,omitempty"`

		// Lat Latitude of the location
		Lat *float32 `json:"lat,omitempty"`

		// Lon Longitude of the location
		Lon *float32 `json:"lon,omitempty"`

		// Utcoffset UTC offset in minutes
		Utcoffset *int `json:"utcoffset,omitempty"`

		// Zip ZIP or postal code
		Zip *string `json:"zip,omitempty"`
	} `json:"geo,omitempty"`
	Regs *struct {
		// Coppa Indicates if COPPA regulations apply
		Coppa *bool `json:"coppa,omitempty"`

		// EuPrivacy EU privacy string indicating compliance
		EuPrivacy *string `json:"eu_privacy,omitempty"`

		// Gdpr Indicates if GDPR regulations apply
		Gdpr *bool `json:"gdpr,omitempty"`

		// Iab IAB-specific settings or values
		Iab *map[string]interface{} `json:"iab,omitempty"`

		// UsPrivacy US privacy string indicating compliance
		UsPrivacy *string `json:"us_privacy,omitempty"`
	} `json:"regs,omitempty"`
	Segment *struct {
		// Ext An extension field for additional information about the segment.
		Ext *string `json:"ext,omitempty"`
		Id  *string `json:"id,omitempty"`
		Uid *string `json:"uid,omitempty"`
	} `json:"segment,omitempty"`
	Session struct {
		// Battery Battery level percentage
		Battery float32 `json:"battery"`

		// CpuUsage CPU usage percentage
		CpuUsage float32 `json:"cpu_usage"`

		// Id Unique identifier for the session
		Id openapi_types.UUID `json:"id"`

		// LaunchMonotonicTs Monotonic timestamp of the session launch
		LaunchMonotonicTs int `json:"launch_monotonic_ts"`

		// LaunchTs Timestamp of the session launch
		LaunchTs int `json:"launch_ts"`

		// MemoryWarningsMonotonicTs Monotonic timestamps when memory warnings occurred
		MemoryWarningsMonotonicTs []int `json:"memory_warnings_monotonic_ts"`

		// MemoryWarningsTs Timestamps when memory warnings occurred
		MemoryWarningsTs []int `json:"memory_warnings_ts"`

		// MonotonicTs Current monotonic timestamp of the session
		MonotonicTs int `json:"monotonic_ts"`

		// RamSize Total size of RAM
		RamSize int `json:"ram_size"`

		// RamUsed Amount of RAM used
		RamUsed int `json:"ram_used"`

		// StartMonotonicTs Monotonic timestamp of the session start
		StartMonotonicTs int `json:"start_monotonic_ts"`

		// StartTs Timestamp of the session start
		StartTs int `json:"start_ts"`

		// StorageFree Free storage space available
		StorageFree *int `json:"storage_free,omitempty"`

		// StorageUsed Used storage space
		StorageUsed *int `json:"storage_used,omitempty"`

		// Ts Current timestamp of the session
		Ts int `json:"ts"`
	} `json:"session"`

	// Test Flag indicating that the request is a test
	Test *bool `json:"test,omitempty"`

	// Tmax Maximum response time for the server before timeout
	Tmax  *int64  `json:"tmax,omitempty"`
	Token *string `json:"token,omitempty"`
	User  struct {
		// Consent Consent settings or preferences
		Consent *map[string]interface{} `json:"consent,omitempty"`

		// Coppa Indicates if COPPA (Children's Online Privacy Protection Act) applies
		Coppa *bool `json:"coppa,omitempty"`

		// Idfa Identifier for Advertisers (IDFA)
		Idfa *openapi_types.UUID `json:"idfa,omitempty"`

		// Idfv Identifier for Vendors (IDFV)
		Idfv *openapi_types.UUID `json:"idfv,omitempty"`

		// Idg Generic identifier (IDG)
		Idg *openapi_types.UUID `json:"idg,omitempty"`

		// TrackingAuthorizationStatus Status of tracking authorization
		TrackingAuthorizationStatus string `json:"tracking_authorization_status"`
	} `json:"user"`
}

// GetAuctionParamsAdType defines parameters for GetAuction.
type GetAuctionParamsAdType string

// GetAuctionJSONBodyAdObjectBannerFormat defines parameters for GetAuction.
type GetAuctionJSONBodyAdObjectBannerFormat string

// GetAuctionJSONBodyAdObjectOrientation defines parameters for GetAuction.
type GetAuctionJSONBodyAdObjectOrientation string

// GetAuctionJSONBodyDeviceConnectionType defines parameters for GetAuction.
type GetAuctionJSONBodyDeviceConnectionType string

// GetAuctionJSONBodyDeviceType defines parameters for GetAuction.
type GetAuctionJSONBodyDeviceType string

// GetConfigJSONBody defines parameters for GetConfig.
type GetConfigJSONBody struct {
	Adapters *map[string]struct {
		SdkVersion string `json:"sdk_version"`
		Version    string `json:"version"`
	} `json:"adapters,omitempty"`
	App *struct {
		// Bundle The bundle identifier of the application, typically in reverse domain name notation (e.g., com.example.myapp).
		Bundle string `json:"bundle"`

		// Framework The name of the framework used by the application (e.g., React Native, Flutter, etc.).
		Framework string `json:"framework"`

		// FrameworkVersion The version of the framework used by the application, specifying compatibility.
		FrameworkVersion *string `json:"framework_version,omitempty"`

		// Key A unique key or identifier for the application.
		Key string `json:"key"`

		// PluginVersion The version of the plugin integrated into the application
		PluginVersion *string `json:"plugin_version,omitempty"`

		// SdkVersion The version of the SDK used in the application.
		SdkVersion *string `json:"sdk_version,omitempty"`

		// Skadn An array of SKAdNetwork IDs for ad attribution, used primarily for iOS applications.
		Skadn *[]string `json:"skadn,omitempty"`

		// Version The version of the application, typically following semantic versioning (e.g., 1.0.0).
		Version string `json:"version"`
	} `json:"app,omitempty"`
	Device *struct {
		// Carrier Carrier
		Carrier *string `json:"carrier,omitempty"`

		// ConnectionType Connection Type
		ConnectionType GetConfigJSONBodyDeviceConnectionType `json:"connection_type"`
		Geo            *struct {
			// Accuracy Accuracy of the location data
			Accuracy *float32 `json:"accuracy,omitempty"`

			// City City name
			City *string `json:"city,omitempty"`

			// Country Country code or name
			Country *string `json:"country,omitempty"`

			// Lastfix Timestamp of the last location fix in seconds since epoch
			Lastfix *int `json:"lastfix,omitempty"`

			// Lat Latitude of the location
			Lat *float32 `json:"lat,omitempty"`

			// Lon Longitude of the location
			Lon *float32 `json:"lon,omitempty"`

			// Utcoffset UTC offset in minutes
			Utcoffset *int `json:"utcoffset,omitempty"`

			// Zip ZIP or postal code
			Zip *string `json:"zip,omitempty"`
		} `json:"geo,omitempty"`

		// H Height
		H int `json:"h"`

		// Hwv Hardware Version
		Hwv string `json:"hwv"`

		// Js JavaScript support
		Js int `json:"js"`

		// Language Language
		Language string `json:"language"`

		// Make Manufacturer
		Make string `json:"make"`

		// Mccmnc Mobile Country Code and Mobile Network Code
		Mccmnc *string `json:"mccmnc,omitempty"`

		// Model Model
		Model string `json:"model"`

		// Os Operating System
		Os string `json:"os"`

		// Osv Operating System Version
		Osv string `json:"osv"`

		// Ppi Pixels per Inch (PPI)
		Ppi int `json:"ppi"`

		// Pxratio Pixel Ratio
		Pxratio float32 `json:"pxratio"`

		// Type Device Type
		Type *GetConfigJSONBodyDeviceType `json:"type,omitempty"`

		// Ua UserAgent
		Ua string `json:"ua"`

		// W Width
		W int `json:"w"`
	} `json:"device,omitempty"`
	Ext *string `json:"ext,omitempty"`
	Geo *struct {
		// Accuracy Accuracy of the location data
		Accuracy *float32 `json:"accuracy,omitempty"`

		// City City name
		City *string `json:"city,omitempty"`

		// Country Country code or name
		Country *string `json:"country,omitempty"`

		// Lastfix Timestamp of the last location fix in seconds since epoch
		Lastfix *int `json:"lastfix,omitempty"`

		// Lat Latitude of the location
		Lat *float32 `json:"lat,omitempty"`

		// Lon Longitude of the location
		Lon *float32 `json:"lon,omitempty"`

		// Utcoffset UTC offset in minutes
		Utcoffset *int `json:"utcoffset,omitempty"`

		// Zip ZIP or postal code
		Zip *string `json:"zip,omitempty"`
	} `json:"geo,omitempty"`
	Regs *struct {
		// Coppa Indicates if COPPA regulations apply
		Coppa *bool `json:"coppa,omitempty"`

		// EuPrivacy EU privacy string indicating compliance
		EuPrivacy *string `json:"eu_privacy,omitempty"`

		// Gdpr Indicates if GDPR regulations apply
		Gdpr *bool `json:"gdpr,omitempty"`

		// Iab IAB-specific settings or values
		Iab *map[string]interface{} `json:"iab,omitempty"`

		// UsPrivacy US privacy string indicating compliance
		UsPrivacy *string `json:"us_privacy,omitempty"`
	} `json:"regs,omitempty"`
	Segment *struct {
		// Ext An extension field for additional information about the segment.
		Ext *string `json:"ext,omitempty"`
		Id  *string `json:"id,omitempty"`
		Uid *string `json:"uid,omitempty"`
	} `json:"segment,omitempty"`
	Session *struct {
		// Battery Battery level percentage
		Battery float32 `json:"battery"`

		// CpuUsage CPU usage percentage
		CpuUsage float32 `json:"cpu_usage"`

		// Id Unique identifier for the session
		Id openapi_types.UUID `json:"id"`

		// LaunchMonotonicTs Monotonic timestamp of the session launch
		LaunchMonotonicTs int `json:"launch_monotonic_ts"`

		// LaunchTs Timestamp of the session launch
		LaunchTs int `json:"launch_ts"`

		// MemoryWarningsMonotonicTs Monotonic timestamps when memory warnings occurred
		MemoryWarningsMonotonicTs []int `json:"memory_warnings_monotonic_ts"`

		// MemoryWarningsTs Timestamps when memory warnings occurred
		MemoryWarningsTs []int `json:"memory_warnings_ts"`

		// MonotonicTs Current monotonic timestamp of the session
		MonotonicTs int `json:"monotonic_ts"`

		// RamSize Total size of RAM
		RamSize int `json:"ram_size"`

		// RamUsed Amount of RAM used
		RamUsed int `json:"ram_used"`

		// StartMonotonicTs Monotonic timestamp of the session start
		StartMonotonicTs int `json:"start_monotonic_ts"`

		// StartTs Timestamp of the session start
		StartTs int `json:"start_ts"`

		// StorageFree Free storage space available
		StorageFree *int `json:"storage_free,omitempty"`

		// StorageUsed Used storage space
		StorageUsed *int `json:"storage_used,omitempty"`

		// Ts Current timestamp of the session
		Ts int `json:"ts"`
	} `json:"session,omitempty"`
	Token *string `json:"token,omitempty"`
	User  *struct {
		// Consent Consent settings or preferences
		Consent *map[string]interface{} `json:"consent,omitempty"`

		// Coppa Indicates if COPPA (Children's Online Privacy Protection Act) applies
		Coppa *bool `json:"coppa,omitempty"`

		// Idfa Identifier for Advertisers (IDFA)
		Idfa *openapi_types.UUID `json:"idfa,omitempty"`

		// Idfv Identifier for Vendors (IDFV)
		Idfv *openapi_types.UUID `json:"idfv,omitempty"`

		// Idg Generic identifier (IDG)
		Idg *openapi_types.UUID `json:"idg,omitempty"`

		// TrackingAuthorizationStatus Status of tracking authorization
		TrackingAuthorizationStatus string `json:"tracking_authorization_status"`
	} `json:"user,omitempty"`
}

// GetConfigJSONBodyDeviceConnectionType defines parameters for GetConfig.
type GetConfigJSONBodyDeviceConnectionType string

// GetConfigJSONBodyDeviceType defines parameters for GetConfig.
type GetConfigJSONBodyDeviceType string

// PostStatsJSONBody defines parameters for PostStats.
type PostStatsJSONBody struct {
	App struct {
		// Bundle The bundle identifier of the application, typically in reverse domain name notation (e.g., com.example.myapp).
		Bundle string `json:"bundle"`

		// Framework The name of the framework used by the application (e.g., React Native, Flutter, etc.).
		Framework string `json:"framework"`

		// FrameworkVersion The version of the framework used by the application, specifying compatibility.
		FrameworkVersion *string `json:"framework_version,omitempty"`

		// Key A unique key or identifier for the application.
		Key string `json:"key"`

		// PluginVersion The version of the plugin integrated into the application
		PluginVersion *string `json:"plugin_version,omitempty"`

		// SdkVersion The version of the SDK used in the application.
		SdkVersion *string `json:"sdk_version,omitempty"`

		// Skadn An array of SKAdNetwork IDs for ad attribution, used primarily for iOS applications.
		Skadn *[]string `json:"skadn,omitempty"`

		// Version The version of the application, typically following semantic versioning (e.g., 1.0.0).
		Version string `json:"version"`
	} `json:"app"`
	Device struct {
		// Carrier Carrier
		Carrier *string `json:"carrier,omitempty"`

		// ConnectionType Connection Type
		ConnectionType PostStatsJSONBodyDeviceConnectionType `json:"connection_type"`
		Geo            *struct {
			// Accuracy Accuracy of the location data
			Accuracy *float32 `json:"accuracy,omitempty"`

			// City City name
			City *string `json:"city,omitempty"`

			// Country Country code or name
			Country *string `json:"country,omitempty"`

			// Lastfix Timestamp of the last location fix in seconds since epoch
			Lastfix *int `json:"lastfix,omitempty"`

			// Lat Latitude of the location
			Lat *float32 `json:"lat,omitempty"`

			// Lon Longitude of the location
			Lon *float32 `json:"lon,omitempty"`

			// Utcoffset UTC offset in minutes
			Utcoffset *int `json:"utcoffset,omitempty"`

			// Zip ZIP or postal code
			Zip *string `json:"zip,omitempty"`
		} `json:"geo,omitempty"`

		// H Height
		H int `json:"h"`

		// Hwv Hardware Version
		Hwv string `json:"hwv"`

		// Js JavaScript support
		Js int `json:"js"`

		// Language Language
		Language string `json:"language"`

		// Make Manufacturer
		Make string `json:"make"`

		// Mccmnc Mobile Country Code and Mobile Network Code
		Mccmnc *string `json:"mccmnc,omitempty"`

		// Model Model
		Model string `json:"model"`

		// Os Operating System
		Os string `json:"os"`

		// Osv Operating System Version
		Osv string `json:"osv"`

		// Ppi Pixels per Inch (PPI)
		Ppi int `json:"ppi"`

		// Pxratio Pixel Ratio
		Pxratio float32 `json:"pxratio"`

		// Type Device Type
		Type *PostStatsJSONBodyDeviceType `json:"type,omitempty"`

		// Ua UserAgent
		Ua string `json:"ua"`

		// W Width
		W int `json:"w"`
	} `json:"device"`
	Ext *string `json:"ext,omitempty"`
	Geo *struct {
		// Accuracy Accuracy of the location data
		Accuracy *float32 `json:"accuracy,omitempty"`

		// City City name
		City *string `json:"city,omitempty"`

		// Country Country code or name
		Country *string `json:"country,omitempty"`

		// Lastfix Timestamp of the last location fix in seconds since epoch
		Lastfix *int `json:"lastfix,omitempty"`

		// Lat Latitude of the location
		Lat *float32 `json:"lat,omitempty"`

		// Lon Longitude of the location
		Lon *float32 `json:"lon,omitempty"`

		// Utcoffset UTC offset in minutes
		Utcoffset *int `json:"utcoffset,omitempty"`

		// Zip ZIP or postal code
		Zip *string `json:"zip,omitempty"`
	} `json:"geo,omitempty"`
	Regs *struct {
		// Coppa Indicates if COPPA regulations apply
		Coppa *bool `json:"coppa,omitempty"`

		// EuPrivacy EU privacy string indicating compliance
		EuPrivacy *string `json:"eu_privacy,omitempty"`

		// Gdpr Indicates if GDPR regulations apply
		Gdpr *bool `json:"gdpr,omitempty"`

		// Iab IAB-specific settings or values
		Iab *map[string]interface{} `json:"iab,omitempty"`

		// UsPrivacy US privacy string indicating compliance
		UsPrivacy *string `json:"us_privacy,omitempty"`
	} `json:"regs,omitempty"`
	Segment *struct {
		// Ext An extension field for additional information about the segment.
		Ext *string `json:"ext,omitempty"`
		Id  *string `json:"id,omitempty"`
		Uid *string `json:"uid,omitempty"`
	} `json:"segment,omitempty"`
	Session struct {
		// Battery Battery level percentage
		Battery float32 `json:"battery"`

		// CpuUsage CPU usage percentage
		CpuUsage float32 `json:"cpu_usage"`

		// Id Unique identifier for the session
		Id openapi_types.UUID `json:"id"`

		// LaunchMonotonicTs Monotonic timestamp of the session launch
		LaunchMonotonicTs int `json:"launch_monotonic_ts"`

		// LaunchTs Timestamp of the session launch
		LaunchTs int `json:"launch_ts"`

		// MemoryWarningsMonotonicTs Monotonic timestamps when memory warnings occurred
		MemoryWarningsMonotonicTs []int `json:"memory_warnings_monotonic_ts"`

		// MemoryWarningsTs Timestamps when memory warnings occurred
		MemoryWarningsTs []int `json:"memory_warnings_ts"`

		// MonotonicTs Current monotonic timestamp of the session
		MonotonicTs int `json:"monotonic_ts"`

		// RamSize Total size of RAM
		RamSize int `json:"ram_size"`

		// RamUsed Amount of RAM used
		RamUsed int `json:"ram_used"`

		// StartMonotonicTs Monotonic timestamp of the session start
		StartMonotonicTs int `json:"start_monotonic_ts"`

		// StartTs Timestamp of the session start
		StartTs int `json:"start_ts"`

		// StorageFree Free storage space available
		StorageFree *int `json:"storage_free,omitempty"`

		// StorageUsed Used storage space
		StorageUsed *int `json:"storage_used,omitempty"`

		// Ts Current timestamp of the session
		Ts int `json:"ts"`
	} `json:"session"`
	Stats PostStatsJSONBody_Stats `json:"stats"`
	Token *string                 `json:"token,omitempty"`
	User  struct {
		// Consent Consent settings or preferences
		Consent *map[string]interface{} `json:"consent,omitempty"`

		// Coppa Indicates if COPPA (Children's Online Privacy Protection Act) applies
		Coppa *bool `json:"coppa,omitempty"`

		// Idfa Identifier for Advertisers (IDFA)
		Idfa *openapi_types.UUID `json:"idfa,omitempty"`

		// Idfv Identifier for Vendors (IDFV)
		Idfv *openapi_types.UUID `json:"idfv,omitempty"`

		// Idg Generic identifier (IDG)
		Idg *openapi_types.UUID `json:"idg,omitempty"`

		// TrackingAuthorizationStatus Status of tracking authorization
		TrackingAuthorizationStatus string `json:"tracking_authorization_status"`
	} `json:"user"`
}

// PostStatsParamsAdType defines parameters for PostStats.
type PostStatsParamsAdType string

// PostStatsJSONBodyDeviceConnectionType defines parameters for PostStats.
type PostStatsJSONBodyDeviceConnectionType string

// PostStatsJSONBodyDeviceType defines parameters for PostStats.
type PostStatsJSONBodyDeviceType string

// PostStatsJSONBodyStatsAdUnitsStatus defines parameters for PostStats.
type PostStatsJSONBodyStatsAdUnitsStatus string

// PostStatsJSONBodyStatsResultBannerFormat defines parameters for PostStats.
type PostStatsJSONBodyStatsResultBannerFormat string

// PostStatsJSONBodyStatsResultBidType defines parameters for PostStats.
type PostStatsJSONBodyStatsResultBidType string

// PostStatsJSONBodyStatsResultStatus defines parameters for PostStats.
type PostStatsJSONBodyStatsResultStatus string

// PostStatsJSONBodyStats0 defines parameters for PostStats.
type PostStatsJSONBodyStats0 = interface{}

// PostStatsJSONBodyStats1 defines parameters for PostStats.
type PostStatsJSONBodyStats1 = interface{}

// PostStatsJSONBody_Stats defines parameters for PostStats.
type PostStatsJSONBody_Stats struct {
	// AdUnits List of results for each ad unit in the auction
	AdUnits []struct {
		// AdUnitLabel Label of the ad unit
		AdUnitLabel *string `json:"ad_unit_label,omitempty"`

		// AdUnitUid UID of the ad unit
		AdUnitUid *string      `json:"ad_unit_uid,omitempty"`
		BidType   *interface{} `json:"bid_type,omitempty"`

		// DemandId ID of the demand source for the ad unit
		DemandId string `json:"demand_id"`

		// ErrorMessage Error message associated with the ad unit, if applicable
		ErrorMessage *string `json:"error_message,omitempty"`

		// FillFinishTs Timestamp when the ad fill finished
		FillFinishTs *int64 `json:"fill_finish_ts,omitempty"`

		// FillStartTs Timestamp when the ad fill started
		FillStartTs *int64 `json:"fill_start_ts,omitempty"`

		// Price Price associated with the ad unit
		Price *float32 `json:"price,omitempty"`

		// Status Status of the ad unit
		Status PostStatsJSONBodyStatsAdUnitsStatus `json:"status"`

		// TokenFinishTs Timestamp when the token process finished
		TokenFinishTs *int64 `json:"token_finish_ts,omitempty"`

		// TokenStartTs Timestamp when the token process started
		TokenStartTs *int64 `json:"token_start_ts,omitempty"`
	} `json:"ad_units"`

	// AuctionConfigurationId ID of the auction configuration
	AuctionConfigurationId *int64 `json:"auction_configuration_id"`

	// AuctionConfigurationUid UID of the auction configuration
	AuctionConfigurationUid *string `json:"auction_configuration_uid"`

	// AuctionId Generated unique identifier for the auction
	AuctionId string `json:"auction_id"`

	// AuctionPricefloor PriceFloor for the auction
	AuctionPricefloor *float32 `json:"auction_pricefloor,omitempty"`
	Result            struct {
		// AuctionFinishTs Timestamp when the auction finished
		AuctionFinishTs *int64 `json:"auction_finish_ts,omitempty"`

		// AuctionStartTs Timestamp when the auction started
		AuctionStartTs *int64 `json:"auction_start_ts,omitempty"`
		Banner         *struct {
			// Format Format of the banner ad
			Format PostStatsJSONBodyStatsResultBannerFormat `json:"format"`
		} `json:"banner,omitempty"`

		// BidType Type of bid (RTB or CPM)
		BidType *PostStatsJSONBodyStatsResultBidType `json:"bid_type,omitempty"`

		// Interstitial Empty schema for interstitial ad configuration
		Interstitial *map[string]interface{} `json:"interstitial,omitempty"`

		// Price Price of the winning bid
		Price *float32 `json:"price,omitempty"`

		// Rewarded Empty schema for rewarded ad configuration
		Rewarded *map[string]interface{} `json:"rewarded,omitempty"`

		// Status Status of the auction
		Status PostStatsJSONBodyStatsResultStatus `json:"status"`

		// WinnerAdUnitLabel Label of the winning ad unit, if applicable
		WinnerAdUnitLabel *string `json:"winner_ad_unit_label,omitempty"`

		// WinnerAdUnitUid UID of the winning ad unit, if applicable
		WinnerAdUnitUid *string `json:"winner_ad_unit_uid,omitempty"`

		// WinnerDemandId ID of the winning demand source, if applicable
		WinnerDemandId *string `json:"winner_demand_id,omitempty"`
	} `json:"result"`
	union json.RawMessage
}

// GetAuctionJSONRequestBody defines body for GetAuction for application/json ContentType.
type GetAuctionJSONRequestBody GetAuctionJSONBody

// GetConfigJSONRequestBody defines body for GetConfig for application/json ContentType.
type GetConfigJSONRequestBody GetConfigJSONBody

// PostStatsJSONRequestBody defines body for PostStats for application/json ContentType.
type PostStatsJSONRequestBody PostStatsJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get OpenAPI specification
	// (GET /openapi.json)
	GetOpenAPISpec(ctx echo.Context) error
	// Auction
	// (POST /v2/auction/{ad_type})
	GetAuction(ctx echo.Context, adType GetAuctionParamsAdType) error
	// Get config
	// (POST /v2/config)
	GetConfig(ctx echo.Context) error
	// Stats
	// (POST v2/stats/{ad_type})
	PostStats(ctx echo.Context, adType PostStatsParamsAdType) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetOpenAPISpec converts echo context to params.
func (w *ServerInterfaceWrapper) GetOpenAPISpec(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetOpenAPISpec(ctx)
	return err
}

// GetAuction converts echo context to params.
func (w *ServerInterfaceWrapper) GetAuction(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "ad_type" -------------
	var adType GetAuctionParamsAdType

	err = runtime.BindStyledParameterWithOptions("simple", "ad_type", ctx.Param("ad_type"), &adType, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter ad_type: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAuction(ctx, adType)
	return err
}

// GetConfig converts echo context to params.
func (w *ServerInterfaceWrapper) GetConfig(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetConfig(ctx)
	return err
}

// PostStats converts echo context to params.
func (w *ServerInterfaceWrapper) PostStats(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "ad_type" -------------
	var adType PostStatsParamsAdType

	err = runtime.BindStyledParameterWithOptions("simple", "ad_type", ctx.Param("ad_type"), &adType, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter ad_type: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostStats(ctx, adType)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/openapi.json", wrapper.GetOpenAPISpec)
	router.POST(baseURL+"/v2/auction/:ad_type", wrapper.GetAuction)
	router.POST(baseURL+"/v2/config", wrapper.GetConfig)
	router.POST(baseURL+"v2/stats/:ad_type", wrapper.PostStats)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xce2/buJb/KoT2AttiFSeTubsL5D/Hdju+kyaGk3SALQqDlo5tTiVSQ1JOPEG++4IP",
	"SZRES3bbNIOLmX+m5uOQPDznx/NSnoKIpRmjQKUILp4CEW0gxfqfOD5ZMZ5iqX78g8TBRdU0MOMGvwtG",
	"gzD4h/kZXAQbKTNxcXqqOk7sIMbXpzHHK3l6fnZ+dvLT+akdHgYxiIiTTBJGg4vgnaaN2ArJDaAlphQ4",
	"wnEQBkDzNLj4FFwOr68n8yAMribD8WR+eTOcj4Mw+DCfjIIwGI6Hs7vpx0nwOQwkkQkEF8GlpjKMb5a/",
	"QySDMJC7TLULyQldB8+hOhQzne45TdPJ9vx7HRXHMVHnxMmMswy4JCCCixVOBIRB5jQ9BTiP1MhFxOiK",
	"rHOO9S+1s6cGx6bjglt2DqrNCcKguMKAUPk//6zOT6iENXDNAO9yuW+9+/4F2/y15L30KPkjB0RioJKs",
	"CHC0Ytwl30XwC+zaFN8DBY4lxOgL7JrUEIc/chCyi2rGSQSrhDHeJj5Tfe9Un2efKaEkVWJ6VlKnebo0",
	"PDbCrCWMwyq4CP7jtFI8KyTi1Iw6qSTyWalIimlsNdInQs1NjvUExBoC71J0h3/AmbrSYpkwgEecZomi",
	"/OkpSEFijQsSy1wEF8Ht/Wg0ub1VdNkXUATM/+3vxYpQIjYLhSY//e9Z9V/RLyTmstX903MYbHO6Virr",
	"LPZuOL367is9f/bwRKkDF5JIgpO+W3LH1u+KcQJUGk1o3ctN1VnqkItts5v53Xw4vVPoNrwe346GM4Nk",
	"TUnl8IB5DHHfPotx7h719D9ywtX0Tz6hryTOQdECPz+e+wQKxyemrcLPu10GGjIHJQB+NXIWDLI61Lgs",
	"hx+1DSO1hT14n1NSR3vV8ApAvyTxouBcXVjU5pWULEmMsBAsIhrTHojcWMlB+hCe85nr8z8XbZw1o5Fg",
	"OY+87IJHuR97JM+hCSjDciSqTlvhZXPjlRgleAlJe9NXqnn//GqnXch9k5VbIhGgVR3DS5qdGJ4f+YLt",
	"22lDB6v7MksUjAgr8agJ9v0e9uEYZ9K+MVquSyCwPd9LwOsyLOIviy1wYTGvdSv7+xp8KAaGNZI+sMZZ",
	"5mhvlr3MwZY5jROfairbVPe5t14gepYlJNIgHyK5y0iEk2SHiDI91JEAxSzFhCKKU0CU2ffgDQzWgxBF",
	"LB3Y53eQ7nCWvR34BH3FcQoPjH/xb06Ttvsph6JcQIyWu+Yui6XngCOJrrEkWwjRuySXEniIQEaDnk24",
	"t9/ejO08eD8hEhlEZLUjdK34kWFJliQhcufdhdcGHCrFU1qpTEDGvcpZreilmyX5mtCjjmamIG1YGwuU",
	"UMmaq/kWa6hQ70q3418N+wg96DDiC449lIcUYc7xTpG9/XUYX4PUNzMdG7jGMcJScrLMzcXoJTNOUsxJ",
	"YmxrcnPrri7U8kRCKrxQYBv0og1o6D3zHsVasSRhD0pWhIJRSaJiomqzsv3T4Gxw5pPiBgJZjTdS5apZ",
	"tVUvHBkj6sTaESccRJ649oW3/zX8ynihNrDofGhL03TvO1uQ6fUQ95NwDR9jwS6JMSJrbOmxZsqVakbM",
	"IaYCcM74IgUh8NoD8RPVjWx3l/0VIrIqRHOZeO2nFUkS11dpyTpJQUicZuhhA7QgrmYhMwviw9x4vVDl",
	"9Byxjp506DLagNrjGveYqp3WVeH0NQnf6va2TBVeQRA6Pql1GGeT6/H0+r3Xe2o5jwcwSs9R1mwEQhx5",
	"LU1n9OjljridDsvSste1JA0sGYNybjCrA92K0EkL1mzH6+CZE7nr8IRrTrq1hjsjKt3EjJ393GGZdk3P",
	"MoNrW6tHXYPtqMoNa4nzGlgfETVES8Za9IcM1nlinnKtk7BOgfaytximZ4jiSe+eYYYpHlqhaoSCE7xG",
	"hMb6yadrJDdYat2w0oaIQBjJWixvyVgC2BBN8WOb6Af8qPAHcRAZowKQJGn1XAjgW+BoCSvGTRfL5RE6",
	"7r2eXPRH/fSYtu7qm684aoTLUnSkOHTUoK3dH8/nzZCnT7UNP3y6bXpez1jxIOYVETpJYN8CgTjInFPH",
	"Hi5jsqUt2oMO+k3xWKh/R+IPisS/TMy8oF6oovfpZLlsRfkJRSlJEiIgYiam3WY1PErgFCeLB0IXlKkz",
	"Wx/Gc7cGh0Aoa6+YiB6UF+9ORJgDAqoMwdiLSpQtliQ+RKI13HGIgGwhRpQhPe/b5fl4QC+hrcH6IhTf",
	"6VDtVZ8uUe+8m7DCheo0YZkZ8Mazm3JUU4Q2ZM4LNOxGTK+L93qunT3RkY6GVZjjLNpireN8DbvUUb7G",
	"12fNDousv5nfXSLG0Wj24a3jUszvLoMwGM0+eB2I75Mq6nSjLLA/EKrDGEutFZ1Y+S05oYN9rxK2C0a1",
	"HK/h/ehuenO9GA2vR5Orq8nYy0F1LuCLY8IRBSsO97sbi/Q9ol+9wEEBioJ6LVDRu0YDTfe6cPudt5Zq",
	"lIjV7HkFzHKqS7pfMzuwyQ/bfECxh8sQAW1X1m19DfD+22s82mv80R5XTcoEdHhVSxLHhK5PjGXjCFmt",
	"/WVyVibYZA2dRSr8oXXbj2JrdpUGtAk8NcznwYGRp5I95pxoZM7v4ZDhQFsN6+0vw6G/oz//jnq8X8Sa",
	"kY1Gx+sUfSj96LVq6zCiDU8i+w1OIp0pWYIjSIvizsJ7/L6OYdNoqYu3Zrr5/TIKHWHOCXgCDyPb4THd",
	"IkYpWKfQ6ySMygFFGVFh8k7ufpnMryd3QRj8Nn03VX7C5Orq/mo4d/65uL/+9frmt2u36Xzx3v35c/3n",
	"P+s//3vhT14cru+b9qF+AbLeSK+jtXnYesZjHj9gDuhjWZnR2tDvnifmX3iLb/VvJPIsY9y/ZoLpOvem",
	"366KHs+CKf4CvsguzVc4kjn3X3gaRSmNPPPYkiSARiynku/QiMWAlIFu24uMuGr3kmWxz3P5oJs945nw",
	"VSYBNzHu252QkPrnbfsndl1TlhGPr0keIREoA46mNNqgN7PZ9K0/5/eoDYU9JNBcd3q8Ur9yjTUaNBVr",
	"9svN9SQIg7vh5dXkziv9Ofa4cAL4cG2jQC0XrT3+NxLLTX/qLFdAo2WtuGV9e+YqjL4oHVNLGO5WTNJK",
	"4Yh3G24cW3JcGJ2tF0ynqCsI1T9fBkHLlRrAqoS+wndHHJy8edtjbRzEMQx1Vt131ALV9EHXwF7I8oui",
	"nOPIVy9kewpvPWG2NirGEvvkOiLSQ2ZE5E4XX/mfHA0xvqfGYI9iN2J8L4EEC7kij13BtmL7WMjqDCvy",
	"qCx6a8wjQWgECDIWbfagsvQBsiQyj6HJIB9vEl9BzxWj64Mp5DJiq5UAz0bu70bI9BkvheYS/PH9P0nW",
	"nv5/05liccaExInmuDfoUgjse2CBt1a8srFKsXUaXyVZ1uvV+KzkIk16bGGBnufkIB1Am1IiO1y/PQFR",
	"h42+/h/C0UYJUJrJHTIzTambszOE43a2rWRANa4rEuU6W+XxncYXspZZluGeDNfoZjYbImcrOki586a0",
	"IF9knGy9sDq5R7YPGeVyE/rKck0Ipv6i83Wc8Z5dvh/P5gdukuDlcSXs0+HliSlDJRESINWOhUKOLU5y",
	"F3Cq68zFfkbc334lIxwsmjvi4pWmVlzfEapm319Bn4pddenS3I7p0iPXc9XHtQ0vZCs9Sm8hLTxKoMK8",
	"t5DEtn62/BCCUAOxagBeslzaihOzU58GmHxC2wT2tjtyclvlRNucqqIzllO64YXK57GU4DN4Lk0HSmAL",
	"ifI+IqCy5u05hlaWL3J/jeZodo90Vw+J44odqthv+SbmJintMchyGm0WKaNMMkoibyb0Q9Grg641M80u",
	"hQydPcaYXqI7xXo4uRRSxneLB8ypArTjty5MPtfQQQUdxJT9zHVSt1n87RZJNUJOzd10nvL7rtx57pGi",
	"SCVKe6/Oy2SO04Ugf/oyz0xZnapP0ZkPP+ydnwvwSO0wVa6Cnaur8b0ETFr+m8VSk+lY4Cih7CLGOF7D",
	"YsXBw7J3HADZIUhkOAKEt5gk9Xyph5yfg/cC4jo5fzlfh1QcIQsNo9l+2lVotB9AHO56b1JvriHBXlXq",
	"0XZHzhyRDUvUdqH3s/u6NA5bryFwLFn984fYGYzCzUp/rHxQ6dHn5/CQkbke+vn4qkRTAmS+oAEcbYqK",
	"gq8tTvR/XPKjaxVpnhils/byS9cu7lnvsFrG6m8A5H+9qkandOyAay+ue09hncYUXpR/lMLpaqxWy336",
	"2s7B1pp/iP7iJLH6213k5RRuKBVufIVaok9X9koP8pXVCM+HXU0mdqT8RR5FIIQn3djseYXYkN1Cjzut",
	"JJiZjAKj6AELZOet8sTjVDd5aNdweWaauqopyxSvZpX69VJBDyqsi3h4DGBkJtXc/4zDCjjQyB8DODy4",
	"8ma0IUnMgf6nQDc0IRTQzEYIZpxJm3ocRvKtKRBz13MDG/EK937lP4y36pwCuEBvpuN3w7eHeDckXm17",
	"SX8EGjNL9uOBZNd78JpELky/mY7fH0RQchx9IXS9wLncME7+xEVtal9Fo52IahN7i/C613Pk/16AJ9nx",
	"rGOgK53vKDVl/CsazqbOV6YXgf5kVaf+MqA4I8FF8PPgbPCzkm0sN/pkp7bPaMvFU7D2hczn+uMIoRX8",
	"JgM6nE3Rv25vrlER4KqXAA1n00GglzVQMI31BUk79TaDyDw5Wqv1Ps7PzqyWyULLqo91T4vNFar85GNJ",
	"K7O5Z5umdmaF7Qu6Z8mMs2UC6X+1l+56HUwazLOdie1QOJ+mmO8MR0puNnb4HAan2/PiBT99wqYS+Vln",
	"2FjxsdM3n2FQ33j9u9m9h/Dc7LC0WzLMcQomj/Cp5X3GSJqMLVE/lRQqOw2n2gi11daurhhQPYz3xV+Q",
	"0X+cx77ylyzeHSVXh9lT1oJoc2jY+htR9bM8f6PYH2jumdeyc3/lGFcii2ss5K9KUP0Vha7MEL3EZTfq",
	"Cz0bM8u/ylU3K9O6due9aAU9RYXXcxhsz41d2ws03/Giw4oVylE78NpnTMjCHfk3hpq6Y+W5Xs2DV5G9",
	"lp/SsTuv7N1aD+r5+f8DAAD//yRHL1o5UgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
