// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/bidon-io/bidon-backend/internal/sdkapi/schema"
	"github.com/bidon-io/bidon-backend/internal/sdkapi/v2/apihandlers"
	"sync"
)

// Ensure, that ShowNotificationHandlerMock does implement apihandlers.ShowNotificationHandler.
// If this is not the case, regenerate this file with moq.
var _ apihandlers.ShowNotificationHandler = &ShowNotificationHandlerMock{}

// ShowNotificationHandlerMock is a mock implementation of apihandlers.ShowNotificationHandler.
//
//	func TestSomethingThatUsesShowNotificationHandler(t *testing.T) {
//
//		// make and configure a mocked apihandlers.ShowNotificationHandler
//		mockedShowNotificationHandler := &ShowNotificationHandlerMock{
//			HandleShowFunc: func(contextMoqParam context.Context, bid *schema.Bid, s1 string, s2 string)  {
//				panic("mock out the HandleShow method")
//			},
//		}
//
//		// use mockedShowNotificationHandler in code that requires apihandlers.ShowNotificationHandler
//		// and then make assertions.
//
//	}
type ShowNotificationHandlerMock struct {
	// HandleShowFunc mocks the HandleShow method.
	HandleShowFunc func(contextMoqParam context.Context, bid *schema.Bid, s1 string, s2 string)

	// calls tracks calls to the methods.
	calls struct {
		// HandleShow holds details about calls to the HandleShow method.
		HandleShow []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// Bid is the bid argument value.
			Bid *schema.Bid
			// S1 is the s1 argument value.
			S1 string
			// S2 is the s2 argument value.
			S2 string
		}
	}
	lockHandleShow sync.RWMutex
}

// HandleShow calls HandleShowFunc.
func (mock *ShowNotificationHandlerMock) HandleShow(contextMoqParam context.Context, bid *schema.Bid, s1 string, s2 string) {
	if mock.HandleShowFunc == nil {
		panic("ShowNotificationHandlerMock.HandleShowFunc: method is nil but ShowNotificationHandler.HandleShow was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		Bid             *schema.Bid
		S1              string
		S2              string
	}{
		ContextMoqParam: contextMoqParam,
		Bid:             bid,
		S1:              s1,
		S2:              s2,
	}
	mock.lockHandleShow.Lock()
	mock.calls.HandleShow = append(mock.calls.HandleShow, callInfo)
	mock.lockHandleShow.Unlock()
	mock.HandleShowFunc(contextMoqParam, bid, s1, s2)
}

// HandleShowCalls gets all the calls that were made to HandleShow.
// Check the length with:
//
//	len(mockedShowNotificationHandler.HandleShowCalls())
func (mock *ShowNotificationHandlerMock) HandleShowCalls() []struct {
	ContextMoqParam context.Context
	Bid             *schema.Bid
	S1              string
	S2              string
} {
	var calls []struct {
		ContextMoqParam context.Context
		Bid             *schema.Bid
		S1              string
		S2              string
	}
	mock.lockHandleShow.RLock()
	calls = mock.calls.HandleShow
	mock.lockHandleShow.RUnlock()
	return calls
}
