// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/bidon-io/bidon-backend/internal/auction"
	"github.com/bidon-io/bidon-backend/internal/sdkapi/schema"
	"github.com/bidon-io/bidon-backend/internal/sdkapi/v2/apihandlers"
	"sync"
)

// Ensure, that WinNotificationHandlerMock does implement apihandlers.WinNotificationHandler.
// If this is not the case, regenerate this file with moq.
var _ apihandlers.WinNotificationHandler = &WinNotificationHandlerMock{}

// WinNotificationHandlerMock is a mock implementation of apihandlers.WinNotificationHandler.
//
//	func TestSomethingThatUsesWinNotificationHandler(t *testing.T) {
//
//		// make and configure a mocked apihandlers.WinNotificationHandler
//		mockedWinNotificationHandler := &WinNotificationHandlerMock{
//			HandleWinFunc: func(ctx context.Context, bid *schema.Bid, config *auction.Config, bundle string, adType string) error {
//				panic("mock out the HandleWin method")
//			},
//		}
//
//		// use mockedWinNotificationHandler in code that requires apihandlers.WinNotificationHandler
//		// and then make assertions.
//
//	}
type WinNotificationHandlerMock struct {
	// HandleWinFunc mocks the HandleWin method.
	HandleWinFunc func(ctx context.Context, bid *schema.Bid, config *auction.Config, bundle string, adType string) error

	// calls tracks calls to the methods.
	calls struct {
		// HandleWin holds details about calls to the HandleWin method.
		HandleWin []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Bid is the bid argument value.
			Bid *schema.Bid
			// Config is the config argument value.
			Config *auction.Config
			// Bundle is the bundle argument value.
			Bundle string
			// AdType is the adType argument value.
			AdType string
		}
	}
	lockHandleWin sync.RWMutex
}

// HandleWin calls HandleWinFunc.
func (mock *WinNotificationHandlerMock) HandleWin(ctx context.Context, bid *schema.Bid, config *auction.Config, bundle string, adType string) error {
	if mock.HandleWinFunc == nil {
		panic("WinNotificationHandlerMock.HandleWinFunc: method is nil but WinNotificationHandler.HandleWin was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Bid    *schema.Bid
		Config *auction.Config
		Bundle string
		AdType string
	}{
		Ctx:    ctx,
		Bid:    bid,
		Config: config,
		Bundle: bundle,
		AdType: adType,
	}
	mock.lockHandleWin.Lock()
	mock.calls.HandleWin = append(mock.calls.HandleWin, callInfo)
	mock.lockHandleWin.Unlock()
	return mock.HandleWinFunc(ctx, bid, config, bundle, adType)
}

// HandleWinCalls gets all the calls that were made to HandleWin.
// Check the length with:
//
//	len(mockedWinNotificationHandler.HandleWinCalls())
func (mock *WinNotificationHandlerMock) HandleWinCalls() []struct {
	Ctx    context.Context
	Bid    *schema.Bid
	Config *auction.Config
	Bundle string
	AdType string
} {
	var calls []struct {
		Ctx    context.Context
		Bid    *schema.Bid
		Config *auction.Config
		Bundle string
		AdType string
	}
	mock.lockHandleWin.RLock()
	calls = mock.calls.HandleWin
	mock.lockHandleWin.RUnlock()
	return calls
}
