// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package admin

import (
	"context"
	"sync"
)

// Ensure, that AppDemandProfileRepoMock does implement AppDemandProfileRepo.
// If this is not the case, regenerate this file with moq.
var _ AppDemandProfileRepo = &AppDemandProfileRepoMock{}

// AppDemandProfileRepoMock is a mock implementation of AppDemandProfileRepo.
//
//	func TestSomethingThatUsesAppDemandProfileRepo(t *testing.T) {
//
//		// make and configure a mocked AppDemandProfileRepo
//		mockedAppDemandProfileRepo := &AppDemandProfileRepoMock{
//			CreateFunc: func(ctx context.Context, attrs *AppDemandProfileAttrs) (*AppDemandProfile, error) {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(ctx context.Context, id int64) error {
//				panic("mock out the Delete method")
//			},
//			FindFunc: func(ctx context.Context, id int64) (*AppDemandProfile, error) {
//				panic("mock out the Find method")
//			},
//			FindOwnedByUserFunc: func(ctx context.Context, userID int64, id int64) (*AppDemandProfile, error) {
//				panic("mock out the FindOwnedByUser method")
//			},
//			ListFunc: func(contextMoqParam context.Context) ([]AppDemandProfile, error) {
//				panic("mock out the List method")
//			},
//			ListOwnedByUserFunc: func(ctx context.Context, userID int64) ([]AppDemandProfile, error) {
//				panic("mock out the ListOwnedByUser method")
//			},
//			UpdateFunc: func(ctx context.Context, id int64, attrs *AppDemandProfileAttrs) (*AppDemandProfile, error) {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedAppDemandProfileRepo in code that requires AppDemandProfileRepo
//		// and then make assertions.
//
//	}
type AppDemandProfileRepoMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, attrs *AppDemandProfileAttrs) (*AppDemandProfile, error)

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, id int64) error

	// FindFunc mocks the Find method.
	FindFunc func(ctx context.Context, id int64) (*AppDemandProfile, error)

	// FindOwnedByUserFunc mocks the FindOwnedByUser method.
	FindOwnedByUserFunc func(ctx context.Context, userID int64, id int64) (*AppDemandProfile, error)

	// ListFunc mocks the List method.
	ListFunc func(contextMoqParam context.Context) ([]AppDemandProfile, error)

	// ListOwnedByUserFunc mocks the ListOwnedByUser method.
	ListOwnedByUserFunc func(ctx context.Context, userID int64) ([]AppDemandProfile, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, id int64, attrs *AppDemandProfileAttrs) (*AppDemandProfile, error)

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Attrs is the attrs argument value.
			Attrs *AppDemandProfileAttrs
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// Find holds details about calls to the Find method.
		Find []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// FindOwnedByUser holds details about calls to the FindOwnedByUser method.
		FindOwnedByUser []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID int64
			// ID is the id argument value.
			ID int64
		}
		// List holds details about calls to the List method.
		List []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
		}
		// ListOwnedByUser holds details about calls to the ListOwnedByUser method.
		ListOwnedByUser []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID int64
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
			// Attrs is the attrs argument value.
			Attrs *AppDemandProfileAttrs
		}
	}
	lockCreate          sync.RWMutex
	lockDelete          sync.RWMutex
	lockFind            sync.RWMutex
	lockFindOwnedByUser sync.RWMutex
	lockList            sync.RWMutex
	lockListOwnedByUser sync.RWMutex
	lockUpdate          sync.RWMutex
}

// Create calls CreateFunc.
func (mock *AppDemandProfileRepoMock) Create(ctx context.Context, attrs *AppDemandProfileAttrs) (*AppDemandProfile, error) {
	if mock.CreateFunc == nil {
		panic("AppDemandProfileRepoMock.CreateFunc: method is nil but AppDemandProfileRepo.Create was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Attrs *AppDemandProfileAttrs
	}{
		Ctx:   ctx,
		Attrs: attrs,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, attrs)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedAppDemandProfileRepo.CreateCalls())
func (mock *AppDemandProfileRepoMock) CreateCalls() []struct {
	Ctx   context.Context
	Attrs *AppDemandProfileAttrs
} {
	var calls []struct {
		Ctx   context.Context
		Attrs *AppDemandProfileAttrs
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *AppDemandProfileRepoMock) Delete(ctx context.Context, id int64) error {
	if mock.DeleteFunc == nil {
		panic("AppDemandProfileRepoMock.DeleteFunc: method is nil but AppDemandProfileRepo.Delete was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, id)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedAppDemandProfileRepo.DeleteCalls())
func (mock *AppDemandProfileRepoMock) DeleteCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Find calls FindFunc.
func (mock *AppDemandProfileRepoMock) Find(ctx context.Context, id int64) (*AppDemandProfile, error) {
	if mock.FindFunc == nil {
		panic("AppDemandProfileRepoMock.FindFunc: method is nil but AppDemandProfileRepo.Find was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockFind.Lock()
	mock.calls.Find = append(mock.calls.Find, callInfo)
	mock.lockFind.Unlock()
	return mock.FindFunc(ctx, id)
}

// FindCalls gets all the calls that were made to Find.
// Check the length with:
//
//	len(mockedAppDemandProfileRepo.FindCalls())
func (mock *AppDemandProfileRepoMock) FindCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockFind.RLock()
	calls = mock.calls.Find
	mock.lockFind.RUnlock()
	return calls
}

// FindOwnedByUser calls FindOwnedByUserFunc.
func (mock *AppDemandProfileRepoMock) FindOwnedByUser(ctx context.Context, userID int64, id int64) (*AppDemandProfile, error) {
	if mock.FindOwnedByUserFunc == nil {
		panic("AppDemandProfileRepoMock.FindOwnedByUserFunc: method is nil but AppDemandProfileRepo.FindOwnedByUser was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID int64
		ID     int64
	}{
		Ctx:    ctx,
		UserID: userID,
		ID:     id,
	}
	mock.lockFindOwnedByUser.Lock()
	mock.calls.FindOwnedByUser = append(mock.calls.FindOwnedByUser, callInfo)
	mock.lockFindOwnedByUser.Unlock()
	return mock.FindOwnedByUserFunc(ctx, userID, id)
}

// FindOwnedByUserCalls gets all the calls that were made to FindOwnedByUser.
// Check the length with:
//
//	len(mockedAppDemandProfileRepo.FindOwnedByUserCalls())
func (mock *AppDemandProfileRepoMock) FindOwnedByUserCalls() []struct {
	Ctx    context.Context
	UserID int64
	ID     int64
} {
	var calls []struct {
		Ctx    context.Context
		UserID int64
		ID     int64
	}
	mock.lockFindOwnedByUser.RLock()
	calls = mock.calls.FindOwnedByUser
	mock.lockFindOwnedByUser.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *AppDemandProfileRepoMock) List(contextMoqParam context.Context) ([]AppDemandProfile, error) {
	if mock.ListFunc == nil {
		panic("AppDemandProfileRepoMock.ListFunc: method is nil but AppDemandProfileRepo.List was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
	}{
		ContextMoqParam: contextMoqParam,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(contextMoqParam)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedAppDemandProfileRepo.ListCalls())
func (mock *AppDemandProfileRepoMock) ListCalls() []struct {
	ContextMoqParam context.Context
} {
	var calls []struct {
		ContextMoqParam context.Context
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// ListOwnedByUser calls ListOwnedByUserFunc.
func (mock *AppDemandProfileRepoMock) ListOwnedByUser(ctx context.Context, userID int64) ([]AppDemandProfile, error) {
	if mock.ListOwnedByUserFunc == nil {
		panic("AppDemandProfileRepoMock.ListOwnedByUserFunc: method is nil but AppDemandProfileRepo.ListOwnedByUser was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID int64
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockListOwnedByUser.Lock()
	mock.calls.ListOwnedByUser = append(mock.calls.ListOwnedByUser, callInfo)
	mock.lockListOwnedByUser.Unlock()
	return mock.ListOwnedByUserFunc(ctx, userID)
}

// ListOwnedByUserCalls gets all the calls that were made to ListOwnedByUser.
// Check the length with:
//
//	len(mockedAppDemandProfileRepo.ListOwnedByUserCalls())
func (mock *AppDemandProfileRepoMock) ListOwnedByUserCalls() []struct {
	Ctx    context.Context
	UserID int64
} {
	var calls []struct {
		Ctx    context.Context
		UserID int64
	}
	mock.lockListOwnedByUser.RLock()
	calls = mock.calls.ListOwnedByUser
	mock.lockListOwnedByUser.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *AppDemandProfileRepoMock) Update(ctx context.Context, id int64, attrs *AppDemandProfileAttrs) (*AppDemandProfile, error) {
	if mock.UpdateFunc == nil {
		panic("AppDemandProfileRepoMock.UpdateFunc: method is nil but AppDemandProfileRepo.Update was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		ID    int64
		Attrs *AppDemandProfileAttrs
	}{
		Ctx:   ctx,
		ID:    id,
		Attrs: attrs,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(ctx, id, attrs)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedAppDemandProfileRepo.UpdateCalls())
func (mock *AppDemandProfileRepoMock) UpdateCalls() []struct {
	Ctx   context.Context
	ID    int64
	Attrs *AppDemandProfileAttrs
} {
	var calls []struct {
		Ctx   context.Context
		ID    int64
		Attrs *AppDemandProfileAttrs
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}
