// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package admin

import (
	"context"
	"github.com/bidon-io/bidon-backend/internal/admin/resource"
	"sync"
)

// Ensure, that AppRepoMock does implement AppRepo.
// If this is not the case, regenerate this file with moq.
var _ AppRepo = &AppRepoMock{}

// AppRepoMock is a mock implementation of AppRepo.
//
//	func TestSomethingThatUsesAppRepo(t *testing.T) {
//
//		// make and configure a mocked AppRepo
//		mockedAppRepo := &AppRepoMock{
//			CreateFunc: func(ctx context.Context, attrs *AppAttrs) (*App, error) {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(ctx context.Context, id int64) error {
//				panic("mock out the Delete method")
//			},
//			FindFunc: func(ctx context.Context, id int64) (*App, error) {
//				panic("mock out the Find method")
//			},
//			FindOwnedByUserFunc: func(ctx context.Context, userID int64, id int64) (*App, error) {
//				panic("mock out the FindOwnedByUser method")
//			},
//			ListFunc: func(contextMoqParam context.Context, stringToStrings map[string][]string) (*resource.Collection[App], error) {
//				panic("mock out the List method")
//			},
//			ListOwnedByUserFunc: func(ctx context.Context, userID int64, qParams map[string][]string) (*resource.Collection[App], error) {
//				panic("mock out the ListOwnedByUser method")
//			},
//			UpdateFunc: func(ctx context.Context, id int64, attrs *AppAttrs) (*App, error) {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedAppRepo in code that requires AppRepo
//		// and then make assertions.
//
//	}
type AppRepoMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, attrs *AppAttrs) (*App, error)

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, id int64) error

	// FindFunc mocks the Find method.
	FindFunc func(ctx context.Context, id int64) (*App, error)

	// FindOwnedByUserFunc mocks the FindOwnedByUser method.
	FindOwnedByUserFunc func(ctx context.Context, userID int64, id int64) (*App, error)

	// ListFunc mocks the List method.
	ListFunc func(contextMoqParam context.Context, stringToStrings map[string][]string) (*resource.Collection[App], error)

	// ListOwnedByUserFunc mocks the ListOwnedByUser method.
	ListOwnedByUserFunc func(ctx context.Context, userID int64, qParams map[string][]string) (*resource.Collection[App], error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, id int64, attrs *AppAttrs) (*App, error)

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Attrs is the attrs argument value.
			Attrs *AppAttrs
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// Find holds details about calls to the Find method.
		Find []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// FindOwnedByUser holds details about calls to the FindOwnedByUser method.
		FindOwnedByUser []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID int64
			// ID is the id argument value.
			ID int64
		}
		// List holds details about calls to the List method.
		List []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// StringToStrings is the stringToStrings argument value.
			StringToStrings map[string][]string
		}
		// ListOwnedByUser holds details about calls to the ListOwnedByUser method.
		ListOwnedByUser []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID int64
			// QParams is the qParams argument value.
			QParams map[string][]string
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
			// Attrs is the attrs argument value.
			Attrs *AppAttrs
		}
	}
	lockCreate          sync.RWMutex
	lockDelete          sync.RWMutex
	lockFind            sync.RWMutex
	lockFindOwnedByUser sync.RWMutex
	lockList            sync.RWMutex
	lockListOwnedByUser sync.RWMutex
	lockUpdate          sync.RWMutex
}

// Create calls CreateFunc.
func (mock *AppRepoMock) Create(ctx context.Context, attrs *AppAttrs) (*App, error) {
	if mock.CreateFunc == nil {
		panic("AppRepoMock.CreateFunc: method is nil but AppRepo.Create was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Attrs *AppAttrs
	}{
		Ctx:   ctx,
		Attrs: attrs,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, attrs)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedAppRepo.CreateCalls())
func (mock *AppRepoMock) CreateCalls() []struct {
	Ctx   context.Context
	Attrs *AppAttrs
} {
	var calls []struct {
		Ctx   context.Context
		Attrs *AppAttrs
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *AppRepoMock) Delete(ctx context.Context, id int64) error {
	if mock.DeleteFunc == nil {
		panic("AppRepoMock.DeleteFunc: method is nil but AppRepo.Delete was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, id)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedAppRepo.DeleteCalls())
func (mock *AppRepoMock) DeleteCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Find calls FindFunc.
func (mock *AppRepoMock) Find(ctx context.Context, id int64) (*App, error) {
	if mock.FindFunc == nil {
		panic("AppRepoMock.FindFunc: method is nil but AppRepo.Find was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockFind.Lock()
	mock.calls.Find = append(mock.calls.Find, callInfo)
	mock.lockFind.Unlock()
	return mock.FindFunc(ctx, id)
}

// FindCalls gets all the calls that were made to Find.
// Check the length with:
//
//	len(mockedAppRepo.FindCalls())
func (mock *AppRepoMock) FindCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockFind.RLock()
	calls = mock.calls.Find
	mock.lockFind.RUnlock()
	return calls
}

// FindOwnedByUser calls FindOwnedByUserFunc.
func (mock *AppRepoMock) FindOwnedByUser(ctx context.Context, userID int64, id int64) (*App, error) {
	if mock.FindOwnedByUserFunc == nil {
		panic("AppRepoMock.FindOwnedByUserFunc: method is nil but AppRepo.FindOwnedByUser was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID int64
		ID     int64
	}{
		Ctx:    ctx,
		UserID: userID,
		ID:     id,
	}
	mock.lockFindOwnedByUser.Lock()
	mock.calls.FindOwnedByUser = append(mock.calls.FindOwnedByUser, callInfo)
	mock.lockFindOwnedByUser.Unlock()
	return mock.FindOwnedByUserFunc(ctx, userID, id)
}

// FindOwnedByUserCalls gets all the calls that were made to FindOwnedByUser.
// Check the length with:
//
//	len(mockedAppRepo.FindOwnedByUserCalls())
func (mock *AppRepoMock) FindOwnedByUserCalls() []struct {
	Ctx    context.Context
	UserID int64
	ID     int64
} {
	var calls []struct {
		Ctx    context.Context
		UserID int64
		ID     int64
	}
	mock.lockFindOwnedByUser.RLock()
	calls = mock.calls.FindOwnedByUser
	mock.lockFindOwnedByUser.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *AppRepoMock) List(contextMoqParam context.Context, stringToStrings map[string][]string) (*resource.Collection[App], error) {
	if mock.ListFunc == nil {
		panic("AppRepoMock.ListFunc: method is nil but AppRepo.List was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		StringToStrings map[string][]string
	}{
		ContextMoqParam: contextMoqParam,
		StringToStrings: stringToStrings,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(contextMoqParam, stringToStrings)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedAppRepo.ListCalls())
func (mock *AppRepoMock) ListCalls() []struct {
	ContextMoqParam context.Context
	StringToStrings map[string][]string
} {
	var calls []struct {
		ContextMoqParam context.Context
		StringToStrings map[string][]string
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// ListOwnedByUser calls ListOwnedByUserFunc.
func (mock *AppRepoMock) ListOwnedByUser(ctx context.Context, userID int64, qParams map[string][]string) (*resource.Collection[App], error) {
	if mock.ListOwnedByUserFunc == nil {
		panic("AppRepoMock.ListOwnedByUserFunc: method is nil but AppRepo.ListOwnedByUser was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		UserID  int64
		QParams map[string][]string
	}{
		Ctx:     ctx,
		UserID:  userID,
		QParams: qParams,
	}
	mock.lockListOwnedByUser.Lock()
	mock.calls.ListOwnedByUser = append(mock.calls.ListOwnedByUser, callInfo)
	mock.lockListOwnedByUser.Unlock()
	return mock.ListOwnedByUserFunc(ctx, userID, qParams)
}

// ListOwnedByUserCalls gets all the calls that were made to ListOwnedByUser.
// Check the length with:
//
//	len(mockedAppRepo.ListOwnedByUserCalls())
func (mock *AppRepoMock) ListOwnedByUserCalls() []struct {
	Ctx     context.Context
	UserID  int64
	QParams map[string][]string
} {
	var calls []struct {
		Ctx     context.Context
		UserID  int64
		QParams map[string][]string
	}
	mock.lockListOwnedByUser.RLock()
	calls = mock.calls.ListOwnedByUser
	mock.lockListOwnedByUser.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *AppRepoMock) Update(ctx context.Context, id int64, attrs *AppAttrs) (*App, error) {
	if mock.UpdateFunc == nil {
		panic("AppRepoMock.UpdateFunc: method is nil but AppRepo.Update was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		ID    int64
		Attrs *AppAttrs
	}{
		Ctx:   ctx,
		ID:    id,
		Attrs: attrs,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(ctx, id, attrs)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedAppRepo.UpdateCalls())
func (mock *AppRepoMock) UpdateCalls() []struct {
	Ctx   context.Context
	ID    int64
	Attrs *AppAttrs
} {
	var calls []struct {
		Ctx   context.Context
		ID    int64
		Attrs *AppAttrs
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}
