// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package admin

import (
	"context"
	"sync"
)

// Ensure, that AllResourceQuerierMock does implement AllResourceQuerier.
// If this is not the case, regenerate this file with moq.
var _ AllResourceQuerier[any] = &AllResourceQuerierMock[any]{}

// AllResourceQuerierMock is a mock implementation of AllResourceQuerier.
//
//	func TestSomethingThatUsesAllResourceQuerier(t *testing.T) {
//
//		// make and configure a mocked AllResourceQuerier
//		mockedAllResourceQuerier := &AllResourceQuerierMock{
//			FindFunc: func(ctx context.Context, id int64) (*Resource, error) {
//				panic("mock out the Find method")
//			},
//			ListFunc: func(contextMoqParam context.Context) ([]Resource, error) {
//				panic("mock out the List method")
//			},
//		}
//
//		// use mockedAllResourceQuerier in code that requires AllResourceQuerier
//		// and then make assertions.
//
//	}
type AllResourceQuerierMock[Resource any] struct {
	// FindFunc mocks the Find method.
	FindFunc func(ctx context.Context, id int64) (*Resource, error)

	// ListFunc mocks the List method.
	ListFunc func(contextMoqParam context.Context) ([]Resource, error)

	// calls tracks calls to the methods.
	calls struct {
		// Find holds details about calls to the Find method.
		Find []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// List holds details about calls to the List method.
		List []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
		}
	}
	lockFind sync.RWMutex
	lockList sync.RWMutex
}

// Find calls FindFunc.
func (mock *AllResourceQuerierMock[Resource]) Find(ctx context.Context, id int64) (*Resource, error) {
	if mock.FindFunc == nil {
		panic("AllResourceQuerierMock.FindFunc: method is nil but AllResourceQuerier.Find was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockFind.Lock()
	mock.calls.Find = append(mock.calls.Find, callInfo)
	mock.lockFind.Unlock()
	return mock.FindFunc(ctx, id)
}

// FindCalls gets all the calls that were made to Find.
// Check the length with:
//
//	len(mockedAllResourceQuerier.FindCalls())
func (mock *AllResourceQuerierMock[Resource]) FindCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockFind.RLock()
	calls = mock.calls.Find
	mock.lockFind.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *AllResourceQuerierMock[Resource]) List(contextMoqParam context.Context) ([]Resource, error) {
	if mock.ListFunc == nil {
		panic("AllResourceQuerierMock.ListFunc: method is nil but AllResourceQuerier.List was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
	}{
		ContextMoqParam: contextMoqParam,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(contextMoqParam)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedAllResourceQuerier.ListCalls())
func (mock *AllResourceQuerierMock[Resource]) ListCalls() []struct {
	ContextMoqParam context.Context
} {
	var calls []struct {
		ContextMoqParam context.Context
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// Ensure, that OwnedResourceQuerierMock does implement OwnedResourceQuerier.
// If this is not the case, regenerate this file with moq.
var _ OwnedResourceQuerier[any] = &OwnedResourceQuerierMock[any]{}

// OwnedResourceQuerierMock is a mock implementation of OwnedResourceQuerier.
//
//	func TestSomethingThatUsesOwnedResourceQuerier(t *testing.T) {
//
//		// make and configure a mocked OwnedResourceQuerier
//		mockedOwnedResourceQuerier := &OwnedResourceQuerierMock{
//			FindOwnedByUserFunc: func(ctx context.Context, userID int64, id int64) (*Resource, error) {
//				panic("mock out the FindOwnedByUser method")
//			},
//			ListOwnedByUserFunc: func(ctx context.Context, userID int64) ([]Resource, error) {
//				panic("mock out the ListOwnedByUser method")
//			},
//		}
//
//		// use mockedOwnedResourceQuerier in code that requires OwnedResourceQuerier
//		// and then make assertions.
//
//	}
type OwnedResourceQuerierMock[Resource any] struct {
	// FindOwnedByUserFunc mocks the FindOwnedByUser method.
	FindOwnedByUserFunc func(ctx context.Context, userID int64, id int64) (*Resource, error)

	// ListOwnedByUserFunc mocks the ListOwnedByUser method.
	ListOwnedByUserFunc func(ctx context.Context, userID int64) ([]Resource, error)

	// calls tracks calls to the methods.
	calls struct {
		// FindOwnedByUser holds details about calls to the FindOwnedByUser method.
		FindOwnedByUser []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID int64
			// ID is the id argument value.
			ID int64
		}
		// ListOwnedByUser holds details about calls to the ListOwnedByUser method.
		ListOwnedByUser []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID int64
		}
	}
	lockFindOwnedByUser sync.RWMutex
	lockListOwnedByUser sync.RWMutex
}

// FindOwnedByUser calls FindOwnedByUserFunc.
func (mock *OwnedResourceQuerierMock[Resource]) FindOwnedByUser(ctx context.Context, userID int64, id int64) (*Resource, error) {
	if mock.FindOwnedByUserFunc == nil {
		panic("OwnedResourceQuerierMock.FindOwnedByUserFunc: method is nil but OwnedResourceQuerier.FindOwnedByUser was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID int64
		ID     int64
	}{
		Ctx:    ctx,
		UserID: userID,
		ID:     id,
	}
	mock.lockFindOwnedByUser.Lock()
	mock.calls.FindOwnedByUser = append(mock.calls.FindOwnedByUser, callInfo)
	mock.lockFindOwnedByUser.Unlock()
	return mock.FindOwnedByUserFunc(ctx, userID, id)
}

// FindOwnedByUserCalls gets all the calls that were made to FindOwnedByUser.
// Check the length with:
//
//	len(mockedOwnedResourceQuerier.FindOwnedByUserCalls())
func (mock *OwnedResourceQuerierMock[Resource]) FindOwnedByUserCalls() []struct {
	Ctx    context.Context
	UserID int64
	ID     int64
} {
	var calls []struct {
		Ctx    context.Context
		UserID int64
		ID     int64
	}
	mock.lockFindOwnedByUser.RLock()
	calls = mock.calls.FindOwnedByUser
	mock.lockFindOwnedByUser.RUnlock()
	return calls
}

// ListOwnedByUser calls ListOwnedByUserFunc.
func (mock *OwnedResourceQuerierMock[Resource]) ListOwnedByUser(ctx context.Context, userID int64) ([]Resource, error) {
	if mock.ListOwnedByUserFunc == nil {
		panic("OwnedResourceQuerierMock.ListOwnedByUserFunc: method is nil but OwnedResourceQuerier.ListOwnedByUser was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID int64
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockListOwnedByUser.Lock()
	mock.calls.ListOwnedByUser = append(mock.calls.ListOwnedByUser, callInfo)
	mock.lockListOwnedByUser.Unlock()
	return mock.ListOwnedByUserFunc(ctx, userID)
}

// ListOwnedByUserCalls gets all the calls that were made to ListOwnedByUser.
// Check the length with:
//
//	len(mockedOwnedResourceQuerier.ListOwnedByUserCalls())
func (mock *OwnedResourceQuerierMock[Resource]) ListOwnedByUserCalls() []struct {
	Ctx    context.Context
	UserID int64
} {
	var calls []struct {
		Ctx    context.Context
		UserID int64
	}
	mock.lockListOwnedByUser.RLock()
	calls = mock.calls.ListOwnedByUser
	mock.lockListOwnedByUser.RUnlock()
	return calls
}

// Ensure, that OwnedOrSharedResourceQuerierMock does implement OwnedOrSharedResourceQuerier.
// If this is not the case, regenerate this file with moq.
var _ OwnedOrSharedResourceQuerier[any] = &OwnedOrSharedResourceQuerierMock[any]{}

// OwnedOrSharedResourceQuerierMock is a mock implementation of OwnedOrSharedResourceQuerier.
//
//	func TestSomethingThatUsesOwnedOrSharedResourceQuerier(t *testing.T) {
//
//		// make and configure a mocked OwnedOrSharedResourceQuerier
//		mockedOwnedOrSharedResourceQuerier := &OwnedOrSharedResourceQuerierMock{
//			FindOwnedByUserOrSharedFunc: func(ctx context.Context, userID int64, id int64) (*Resource, error) {
//				panic("mock out the FindOwnedByUserOrShared method")
//			},
//			ListOwnedByUserOrSharedFunc: func(ctx context.Context, userID int64) ([]Resource, error) {
//				panic("mock out the ListOwnedByUserOrShared method")
//			},
//		}
//
//		// use mockedOwnedOrSharedResourceQuerier in code that requires OwnedOrSharedResourceQuerier
//		// and then make assertions.
//
//	}
type OwnedOrSharedResourceQuerierMock[Resource any] struct {
	// FindOwnedByUserOrSharedFunc mocks the FindOwnedByUserOrShared method.
	FindOwnedByUserOrSharedFunc func(ctx context.Context, userID int64, id int64) (*Resource, error)

	// ListOwnedByUserOrSharedFunc mocks the ListOwnedByUserOrShared method.
	ListOwnedByUserOrSharedFunc func(ctx context.Context, userID int64) ([]Resource, error)

	// calls tracks calls to the methods.
	calls struct {
		// FindOwnedByUserOrShared holds details about calls to the FindOwnedByUserOrShared method.
		FindOwnedByUserOrShared []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID int64
			// ID is the id argument value.
			ID int64
		}
		// ListOwnedByUserOrShared holds details about calls to the ListOwnedByUserOrShared method.
		ListOwnedByUserOrShared []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID int64
		}
	}
	lockFindOwnedByUserOrShared sync.RWMutex
	lockListOwnedByUserOrShared sync.RWMutex
}

// FindOwnedByUserOrShared calls FindOwnedByUserOrSharedFunc.
func (mock *OwnedOrSharedResourceQuerierMock[Resource]) FindOwnedByUserOrShared(ctx context.Context, userID int64, id int64) (*Resource, error) {
	if mock.FindOwnedByUserOrSharedFunc == nil {
		panic("OwnedOrSharedResourceQuerierMock.FindOwnedByUserOrSharedFunc: method is nil but OwnedOrSharedResourceQuerier.FindOwnedByUserOrShared was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID int64
		ID     int64
	}{
		Ctx:    ctx,
		UserID: userID,
		ID:     id,
	}
	mock.lockFindOwnedByUserOrShared.Lock()
	mock.calls.FindOwnedByUserOrShared = append(mock.calls.FindOwnedByUserOrShared, callInfo)
	mock.lockFindOwnedByUserOrShared.Unlock()
	return mock.FindOwnedByUserOrSharedFunc(ctx, userID, id)
}

// FindOwnedByUserOrSharedCalls gets all the calls that were made to FindOwnedByUserOrShared.
// Check the length with:
//
//	len(mockedOwnedOrSharedResourceQuerier.FindOwnedByUserOrSharedCalls())
func (mock *OwnedOrSharedResourceQuerierMock[Resource]) FindOwnedByUserOrSharedCalls() []struct {
	Ctx    context.Context
	UserID int64
	ID     int64
} {
	var calls []struct {
		Ctx    context.Context
		UserID int64
		ID     int64
	}
	mock.lockFindOwnedByUserOrShared.RLock()
	calls = mock.calls.FindOwnedByUserOrShared
	mock.lockFindOwnedByUserOrShared.RUnlock()
	return calls
}

// ListOwnedByUserOrShared calls ListOwnedByUserOrSharedFunc.
func (mock *OwnedOrSharedResourceQuerierMock[Resource]) ListOwnedByUserOrShared(ctx context.Context, userID int64) ([]Resource, error) {
	if mock.ListOwnedByUserOrSharedFunc == nil {
		panic("OwnedOrSharedResourceQuerierMock.ListOwnedByUserOrSharedFunc: method is nil but OwnedOrSharedResourceQuerier.ListOwnedByUserOrShared was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID int64
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockListOwnedByUserOrShared.Lock()
	mock.calls.ListOwnedByUserOrShared = append(mock.calls.ListOwnedByUserOrShared, callInfo)
	mock.lockListOwnedByUserOrShared.Unlock()
	return mock.ListOwnedByUserOrSharedFunc(ctx, userID)
}

// ListOwnedByUserOrSharedCalls gets all the calls that were made to ListOwnedByUserOrShared.
// Check the length with:
//
//	len(mockedOwnedOrSharedResourceQuerier.ListOwnedByUserOrSharedCalls())
func (mock *OwnedOrSharedResourceQuerierMock[Resource]) ListOwnedByUserOrSharedCalls() []struct {
	Ctx    context.Context
	UserID int64
} {
	var calls []struct {
		Ctx    context.Context
		UserID int64
	}
	mock.lockListOwnedByUserOrShared.RLock()
	calls = mock.calls.ListOwnedByUserOrShared
	mock.lockListOwnedByUserOrShared.RUnlock()
	return calls
}
