// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package admin

import (
	"context"
	"github.com/bidon-io/bidon-backend/internal/admin/resource"
	"sync"
)

// Ensure, that UserRepoMock does implement UserRepo.
// If this is not the case, regenerate this file with moq.
var _ UserRepo = &UserRepoMock{}

// UserRepoMock is a mock implementation of UserRepo.
//
//	func TestSomethingThatUsesUserRepo(t *testing.T) {
//
//		// make and configure a mocked UserRepo
//		mockedUserRepo := &UserRepoMock{
//			CreateFunc: func(ctx context.Context, attrs *UserAttrs) (*User, error) {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(ctx context.Context, id int64) error {
//				panic("mock out the Delete method")
//			},
//			FindFunc: func(ctx context.Context, id int64) (*User, error) {
//				panic("mock out the Find method")
//			},
//			ListFunc: func(contextMoqParam context.Context, stringToStrings map[string][]string) (*resource.Collection[User], error) {
//				panic("mock out the List method")
//			},
//			UpdateFunc: func(ctx context.Context, id int64, attrs *UserAttrs) (*User, error) {
//				panic("mock out the Update method")
//			},
//			UpdatePasswordFunc: func(ctx context.Context, userID int64, currentPassword string, newPassword string) error {
//				panic("mock out the UpdatePassword method")
//			},
//		}
//
//		// use mockedUserRepo in code that requires UserRepo
//		// and then make assertions.
//
//	}
type UserRepoMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, attrs *UserAttrs) (*User, error)

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, id int64) error

	// FindFunc mocks the Find method.
	FindFunc func(ctx context.Context, id int64) (*User, error)

	// ListFunc mocks the List method.
	ListFunc func(contextMoqParam context.Context, stringToStrings map[string][]string) (*resource.Collection[User], error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, id int64, attrs *UserAttrs) (*User, error)

	// UpdatePasswordFunc mocks the UpdatePassword method.
	UpdatePasswordFunc func(ctx context.Context, userID int64, currentPassword string, newPassword string) error

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Attrs is the attrs argument value.
			Attrs *UserAttrs
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// Find holds details about calls to the Find method.
		Find []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// List holds details about calls to the List method.
		List []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// StringToStrings is the stringToStrings argument value.
			StringToStrings map[string][]string
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
			// Attrs is the attrs argument value.
			Attrs *UserAttrs
		}
		// UpdatePassword holds details about calls to the UpdatePassword method.
		UpdatePassword []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID int64
			// CurrentPassword is the currentPassword argument value.
			CurrentPassword string
			// NewPassword is the newPassword argument value.
			NewPassword string
		}
	}
	lockCreate         sync.RWMutex
	lockDelete         sync.RWMutex
	lockFind           sync.RWMutex
	lockList           sync.RWMutex
	lockUpdate         sync.RWMutex
	lockUpdatePassword sync.RWMutex
}

// Create calls CreateFunc.
func (mock *UserRepoMock) Create(ctx context.Context, attrs *UserAttrs) (*User, error) {
	if mock.CreateFunc == nil {
		panic("UserRepoMock.CreateFunc: method is nil but UserRepo.Create was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Attrs *UserAttrs
	}{
		Ctx:   ctx,
		Attrs: attrs,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, attrs)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedUserRepo.CreateCalls())
func (mock *UserRepoMock) CreateCalls() []struct {
	Ctx   context.Context
	Attrs *UserAttrs
} {
	var calls []struct {
		Ctx   context.Context
		Attrs *UserAttrs
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *UserRepoMock) Delete(ctx context.Context, id int64) error {
	if mock.DeleteFunc == nil {
		panic("UserRepoMock.DeleteFunc: method is nil but UserRepo.Delete was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, id)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedUserRepo.DeleteCalls())
func (mock *UserRepoMock) DeleteCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Find calls FindFunc.
func (mock *UserRepoMock) Find(ctx context.Context, id int64) (*User, error) {
	if mock.FindFunc == nil {
		panic("UserRepoMock.FindFunc: method is nil but UserRepo.Find was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockFind.Lock()
	mock.calls.Find = append(mock.calls.Find, callInfo)
	mock.lockFind.Unlock()
	return mock.FindFunc(ctx, id)
}

// FindCalls gets all the calls that were made to Find.
// Check the length with:
//
//	len(mockedUserRepo.FindCalls())
func (mock *UserRepoMock) FindCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockFind.RLock()
	calls = mock.calls.Find
	mock.lockFind.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *UserRepoMock) List(contextMoqParam context.Context, stringToStrings map[string][]string) (*resource.Collection[User], error) {
	if mock.ListFunc == nil {
		panic("UserRepoMock.ListFunc: method is nil but UserRepo.List was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
		StringToStrings map[string][]string
	}{
		ContextMoqParam: contextMoqParam,
		StringToStrings: stringToStrings,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(contextMoqParam, stringToStrings)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedUserRepo.ListCalls())
func (mock *UserRepoMock) ListCalls() []struct {
	ContextMoqParam context.Context
	StringToStrings map[string][]string
} {
	var calls []struct {
		ContextMoqParam context.Context
		StringToStrings map[string][]string
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *UserRepoMock) Update(ctx context.Context, id int64, attrs *UserAttrs) (*User, error) {
	if mock.UpdateFunc == nil {
		panic("UserRepoMock.UpdateFunc: method is nil but UserRepo.Update was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		ID    int64
		Attrs *UserAttrs
	}{
		Ctx:   ctx,
		ID:    id,
		Attrs: attrs,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(ctx, id, attrs)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedUserRepo.UpdateCalls())
func (mock *UserRepoMock) UpdateCalls() []struct {
	Ctx   context.Context
	ID    int64
	Attrs *UserAttrs
} {
	var calls []struct {
		Ctx   context.Context
		ID    int64
		Attrs *UserAttrs
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}

// UpdatePassword calls UpdatePasswordFunc.
func (mock *UserRepoMock) UpdatePassword(ctx context.Context, userID int64, currentPassword string, newPassword string) error {
	if mock.UpdatePasswordFunc == nil {
		panic("UserRepoMock.UpdatePasswordFunc: method is nil but UserRepo.UpdatePassword was just called")
	}
	callInfo := struct {
		Ctx             context.Context
		UserID          int64
		CurrentPassword string
		NewPassword     string
	}{
		Ctx:             ctx,
		UserID:          userID,
		CurrentPassword: currentPassword,
		NewPassword:     newPassword,
	}
	mock.lockUpdatePassword.Lock()
	mock.calls.UpdatePassword = append(mock.calls.UpdatePassword, callInfo)
	mock.lockUpdatePassword.Unlock()
	return mock.UpdatePasswordFunc(ctx, userID, currentPassword, newPassword)
}

// UpdatePasswordCalls gets all the calls that were made to UpdatePassword.
// Check the length with:
//
//	len(mockedUserRepo.UpdatePasswordCalls())
func (mock *UserRepoMock) UpdatePasswordCalls() []struct {
	Ctx             context.Context
	UserID          int64
	CurrentPassword string
	NewPassword     string
} {
	var calls []struct {
		Ctx             context.Context
		UserID          int64
		CurrentPassword string
		NewPassword     string
	}
	mock.lockUpdatePassword.RLock()
	calls = mock.calls.UpdatePassword
	mock.lockUpdatePassword.RUnlock()
	return calls
}
