//*
// Make it easy to include adcom by providing a single point of entry.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: com/iabtechlab/adcom/v1/adcom.proto

package adcomv1

import (
	context "github.com/bidon-io/bidon-backend/pkg/proto/com/iabtechlab/adcom/v1/context"
	enums "github.com/bidon-io/bidon-backend/pkg/proto/com/iabtechlab/adcom/v1/enums"
	media "github.com/bidon-io/bidon-backend/pkg/proto/com/iabtechlab/adcom/v1/media"
	placement "github.com/bidon-io/bidon-backend/pkg/proto/com/iabtechlab/adcom/v1/placement"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Symbols defined in public import of com/iabtechlab/adcom/v1/enums/enums.proto.

type AgentType = enums.AgentType

const AgentType_AgentType_UNKNOWN = enums.AgentType_AgentType_UNKNOWN
const AgentType_WEB = enums.AgentType_WEB
const AgentType_APP = enums.AgentType_APP
const AgentType_PERSON_BASED = enums.AgentType_PERSON_BASED

var AgentType_name = enums.AgentType_name
var AgentType_value = enums.AgentType_value

type APIFramework = enums.APIFramework

const APIFramework_APIFramework_UNKNOWN = enums.APIFramework_APIFramework_UNKNOWN
const APIFramework_VPAID_1_0 = enums.APIFramework_VPAID_1_0
const APIFramework_VPAID_2_0 = enums.APIFramework_VPAID_2_0
const APIFramework_MRAID_1_0 = enums.APIFramework_MRAID_1_0
const APIFramework_ORMMA = enums.APIFramework_ORMMA
const APIFramework_MRAID_2_0 = enums.APIFramework_MRAID_2_0
const APIFramework_MRAID_3_0 = enums.APIFramework_MRAID_3_0
const APIFramework_OMID_1_0 = enums.APIFramework_OMID_1_0
const APIFramework_SIMID_1_0 = enums.APIFramework_SIMID_1_0
const APIFramework_SIMID_1_1 = enums.APIFramework_SIMID_1_1

var APIFramework_name = enums.APIFramework_name
var APIFramework_value = enums.APIFramework_value

type AuditStatusCode = enums.AuditStatusCode

const AuditStatusCode_AuditStatusCode_UNKNOWN = enums.AuditStatusCode_AuditStatusCode_UNKNOWN
const AuditStatusCode_PENDING_AUDIT = enums.AuditStatusCode_PENDING_AUDIT
const AuditStatusCode_PREAPPROVED = enums.AuditStatusCode_PREAPPROVED
const AuditStatusCode_APPROVED = enums.AuditStatusCode_APPROVED
const AuditStatusCode_DENIED = enums.AuditStatusCode_DENIED
const AuditStatusCode_CHANGE_RESUBMIT = enums.AuditStatusCode_CHANGE_RESUBMIT

var AuditStatusCode_name = enums.AuditStatusCode_name
var AuditStatusCode_value = enums.AuditStatusCode_value

type CategoryTaxonomy = enums.CategoryTaxonomy

const CategoryTaxonomy_CategoryTaxonomy_UNKNOWN = enums.CategoryTaxonomy_CategoryTaxonomy_UNKNOWN
const CategoryTaxonomy_IAB_CONTENT_CAT_TAX_1_0 = enums.CategoryTaxonomy_IAB_CONTENT_CAT_TAX_1_0
const CategoryTaxonomy_IAB_CONTENT_CAT_TAX_2_0 = enums.CategoryTaxonomy_IAB_CONTENT_CAT_TAX_2_0
const CategoryTaxonomy_IAB_AD_PROD_TAX_1_0 = enums.CategoryTaxonomy_IAB_AD_PROD_TAX_1_0
const CategoryTaxonomy_IAB_AUDIENCE_TAX_1_1 = enums.CategoryTaxonomy_IAB_AUDIENCE_TAX_1_1
const CategoryTaxonomy_IAB_CONTENT_CAT_TAX_2_1 = enums.CategoryTaxonomy_IAB_CONTENT_CAT_TAX_2_1
const CategoryTaxonomy_IAB_CONTENT_CAT_TAX_2_2 = enums.CategoryTaxonomy_IAB_CONTENT_CAT_TAX_2_2

var CategoryTaxonomy_name = enums.CategoryTaxonomy_name
var CategoryTaxonomy_value = enums.CategoryTaxonomy_value

type ClickType = enums.ClickType

const ClickType_NON_CLICKABLE = enums.ClickType_NON_CLICKABLE
const ClickType_CLICKABLE_UNKNOWN = enums.ClickType_CLICKABLE_UNKNOWN
const ClickType_CLICKABLE_EMBEDDED = enums.ClickType_CLICKABLE_EMBEDDED
const ClickType_CLICKABLE_NATIVE = enums.ClickType_CLICKABLE_NATIVE

var ClickType_name = enums.ClickType_name
var ClickType_value = enums.ClickType_value

type CompanionType = enums.CompanionType

const CompanionType_CompanionType_UNKNOWN = enums.CompanionType_CompanionType_UNKNOWN
const CompanionType_STATIC_RSRC = enums.CompanionType_STATIC_RSRC
const CompanionType_HTML_RSRC = enums.CompanionType_HTML_RSRC
const CompanionType_IFRAME_RSRC = enums.CompanionType_IFRAME_RSRC

var CompanionType_name = enums.CompanionType_name
var CompanionType_value = enums.CompanionType_value

type ConnectionType = enums.ConnectionType

const ConnectionType_ConnectionType_UNKNOWN = enums.ConnectionType_ConnectionType_UNKNOWN
const ConnectionType_WIRED = enums.ConnectionType_WIRED
const ConnectionType_WIFI = enums.ConnectionType_WIFI
const ConnectionType_CELL_UNKNOWN = enums.ConnectionType_CELL_UNKNOWN
const ConnectionType_CELL_2G = enums.ConnectionType_CELL_2G
const ConnectionType_CELL_3G = enums.ConnectionType_CELL_3G
const ConnectionType_CELL_4G = enums.ConnectionType_CELL_4G
const ConnectionType_CELL_5G = enums.ConnectionType_CELL_5G

var ConnectionType_name = enums.ConnectionType_name
var ConnectionType_value = enums.ConnectionType_value

type ContentContext = enums.ContentContext

const ContentContext_ContentContext_UNKNOWN = enums.ContentContext_ContentContext_UNKNOWN
const ContentContext_VIDEO = enums.ContentContext_VIDEO
const ContentContext_GAME = enums.ContentContext_GAME
const ContentContext_MUSIC = enums.ContentContext_MUSIC
const ContentContext_APPLICATION = enums.ContentContext_APPLICATION
const ContentContext_TEXT = enums.ContentContext_TEXT
const ContentContext_OTHER = enums.ContentContext_OTHER
const ContentContext_NOTKNOWN = enums.ContentContext_NOTKNOWN

var ContentContext_name = enums.ContentContext_name
var ContentContext_value = enums.ContentContext_value

type DeliveryMethod = enums.DeliveryMethod

const DeliveryMethod_DeliveryMethod_UNKNOWN = enums.DeliveryMethod_DeliveryMethod_UNKNOWN
const DeliveryMethod_STREAMING = enums.DeliveryMethod_STREAMING
const DeliveryMethod_PROGRESSIVE = enums.DeliveryMethod_PROGRESSIVE
const DeliveryMethod_DOWNLOAD = enums.DeliveryMethod_DOWNLOAD

var DeliveryMethod_name = enums.DeliveryMethod_name
var DeliveryMethod_value = enums.DeliveryMethod_value

type DeviceType = enums.DeviceType

const DeviceType_DeviceType_UNKNOWN = enums.DeviceType_DeviceType_UNKNOWN
const DeviceType_MOBILE_TABLET = enums.DeviceType_MOBILE_TABLET
const DeviceType_PC = enums.DeviceType_PC
const DeviceType_CONNECTED_TV = enums.DeviceType_CONNECTED_TV
const DeviceType_PHONE = enums.DeviceType_PHONE
const DeviceType_TABLET = enums.DeviceType_TABLET
const DeviceType_CONNECTED_DEV = enums.DeviceType_CONNECTED_DEV
const DeviceType_SET_TOP_BOX = enums.DeviceType_SET_TOP_BOX
const DeviceType_OOH_DEVICE = enums.DeviceType_OOH_DEVICE

var DeviceType_name = enums.DeviceType_name
var DeviceType_value = enums.DeviceType_value

type DisplayContextType = enums.DisplayContextType

const DisplayContextType_DisplayContextType_UNKNOWN = enums.DisplayContextType_DisplayContextType_UNKNOWN
const DisplayContextType_CONTENT_CENTRIC = enums.DisplayContextType_CONTENT_CENTRIC
const DisplayContextType_ARTICLE = enums.DisplayContextType_ARTICLE
const DisplayContextType_VIDEO_X = enums.DisplayContextType_VIDEO_X
const DisplayContextType_AUDIO = enums.DisplayContextType_AUDIO
const DisplayContextType_IMAGE = enums.DisplayContextType_IMAGE
const DisplayContextType_USER_GENERATED = enums.DisplayContextType_USER_GENERATED
const DisplayContextType_SOCIAL = enums.DisplayContextType_SOCIAL
const DisplayContextType_EMAIL = enums.DisplayContextType_EMAIL
const DisplayContextType_CHAT = enums.DisplayContextType_CHAT
const DisplayContextType_PRODUCT = enums.DisplayContextType_PRODUCT
const DisplayContextType_APP_STORE = enums.DisplayContextType_APP_STORE
const DisplayContextType_PRODUCT_REVIEWS = enums.DisplayContextType_PRODUCT_REVIEWS

var DisplayContextType_name = enums.DisplayContextType_name
var DisplayContextType_value = enums.DisplayContextType_value

type DisplayPlacementType = enums.DisplayPlacementType

const DisplayPlacementType_DisplayPlacementType_UNKNOWN = enums.DisplayPlacementType_DisplayPlacementType_UNKNOWN
const DisplayPlacementType_FEED_CONTENT = enums.DisplayPlacementType_FEED_CONTENT
const DisplayPlacementType_ATOMIC_CONTENT = enums.DisplayPlacementType_ATOMIC_CONTENT
const DisplayPlacementType_OUTSIDE_CONTENT = enums.DisplayPlacementType_OUTSIDE_CONTENT
const DisplayPlacementType_RECOMMENDATION = enums.DisplayPlacementType_RECOMMENDATION

var DisplayPlacementType_name = enums.DisplayPlacementType_name
var DisplayPlacementType_value = enums.DisplayPlacementType_value

type DOOHVenueType = enums.DOOHVenueType

const DOOHVenueType_DOOHVenueType_UNKNOWN = enums.DOOHVenueType_DOOHVenueType_UNKNOWN
const DOOHVenueType_AIRBORNE = enums.DOOHVenueType_AIRBORNE
const DOOHVenueType_AIRPORT_GENERAL = enums.DOOHVenueType_AIRPORT_GENERAL
const DOOHVenueType_AIRPORT_BAG_CLAIM = enums.DOOHVenueType_AIRPORT_BAG_CLAIM
const DOOHVenueType_AIRPORT_TERMINAL = enums.DOOHVenueType_AIRPORT_TERMINAL
const DOOHVenueType_AIRPORT_LOUNGE = enums.DOOHVenueType_AIRPORT_LOUNGE
const DOOHVenueType_ATM = enums.DOOHVenueType_ATM
const DOOHVenueType_BACKLIGHT = enums.DOOHVenueType_BACKLIGHT
const DOOHVenueType_BAR = enums.DOOHVenueType_BAR
const DOOHVenueType_BENCH = enums.DOOHVenueType_BENCH
const DOOHVenueType_BIKE_RACK = enums.DOOHVenueType_BIKE_RACK
const DOOHVenueType_BULLETIN = enums.DOOHVenueType_BULLETIN
const DOOHVenueType_BUS = enums.DOOHVenueType_BUS
const DOOHVenueType_CAFE = enums.DOOHVenueType_CAFE
const DOOHVenueType_CASUAL_DINING = enums.DOOHVenueType_CASUAL_DINING
const DOOHVenueType_CHILD_CARE = enums.DOOHVenueType_CHILD_CARE
const DOOHVenueType_CINEMA = enums.DOOHVenueType_CINEMA
const DOOHVenueType_CITY_INFO_PANEL = enums.DOOHVenueType_CITY_INFO_PANEL
const DOOHVenueType_CONVENIENCE_STORE = enums.DOOHVenueType_CONVENIENCE_STORE
const DOOHVenueType_DED_WILD_POSTING = enums.DOOHVenueType_DED_WILD_POSTING
const DOOHVenueType_DOC_OFFICE_GEN = enums.DOOHVenueType_DOC_OFFICE_GEN
const DOOHVenueType_DOC_OFFICE_OB = enums.DOOHVenueType_DOC_OFFICE_OB
const DOOHVenueType_DOC_OFFICE_PEDS = enums.DOOHVenueType_DOC_OFFICE_PEDS
const DOOHVenueType_FAMILY_ENT = enums.DOOHVenueType_FAMILY_ENT
const DOOHVenueType_FERRY = enums.DOOHVenueType_FERRY
const DOOHVenueType_FINANCIAL_SERVICE = enums.DOOHVenueType_FINANCIAL_SERVICE
const DOOHVenueType_GAS_STATION = enums.DOOHVenueType_GAS_STATION
const DOOHVenueType_GOLF_COURSE = enums.DOOHVenueType_GOLF_COURSE
const DOOHVenueType_GYM = enums.DOOHVenueType_GYM
const DOOHVenueType_HOSPITAL = enums.DOOHVenueType_HOSPITAL
const DOOHVenueType_HOTEL = enums.DOOHVenueType_HOTEL
const DOOHVenueType_JR_POSTER = enums.DOOHVenueType_JR_POSTER
const DOOHVenueType_KIOSK = enums.DOOHVenueType_KIOSK
const DOOHVenueType_MALL_GENERAL = enums.DOOHVenueType_MALL_GENERAL
const DOOHVenueType_MALL_FOOD_COURT = enums.DOOHVenueType_MALL_FOOD_COURT
const DOOHVenueType_MARINE = enums.DOOHVenueType_MARINE
const DOOHVenueType_MOBILE_BILLBOARD = enums.DOOHVenueType_MOBILE_BILLBOARD
const DOOHVenueType_MOVIE_THEATER_LOB = enums.DOOHVenueType_MOVIE_THEATER_LOB
const DOOHVenueType_NEWSSTAND = enums.DOOHVenueType_NEWSSTAND
const DOOHVenueType_OFFICE_BUILDING = enums.DOOHVenueType_OFFICE_BUILDING
const DOOHVenueType_PHONE_KIOSK = enums.DOOHVenueType_PHONE_KIOSK
const DOOHVenueType_POSTER = enums.DOOHVenueType_POSTER
const DOOHVenueType_QSR = enums.DOOHVenueType_QSR
const DOOHVenueType_RAIL = enums.DOOHVenueType_RAIL
const DOOHVenueType_RECEPTACLE = enums.DOOHVenueType_RECEPTACLE
const DOOHVenueType_RESORT = enums.DOOHVenueType_RESORT
const DOOHVenueType_RETAIL = enums.DOOHVenueType_RETAIL
const DOOHVenueType_SALON = enums.DOOHVenueType_SALON
const DOOHVenueType_SHELTER = enums.DOOHVenueType_SHELTER
const DOOHVenueType_SPORTS_ARENA = enums.DOOHVenueType_SPORTS_ARENA
const DOOHVenueType_SUBWAY = enums.DOOHVenueType_SUBWAY
const DOOHVenueType_TAXI_WRAP_VEHICLE = enums.DOOHVenueType_TAXI_WRAP_VEHICLE
const DOOHVenueType_TRUCKSIDE = enums.DOOHVenueType_TRUCKSIDE
const DOOHVenueType_UNIVERSITY = enums.DOOHVenueType_UNIVERSITY
const DOOHVenueType_URBAN_PANEL = enums.DOOHVenueType_URBAN_PANEL
const DOOHVenueType_VET_OFFICE = enums.DOOHVenueType_VET_OFFICE
const DOOHVenueType_WALL_SPECTACULAR = enums.DOOHVenueType_WALL_SPECTACULAR
const DOOHVenueType_OTHER_X = enums.DOOHVenueType_OTHER_X

var DOOHVenueType_name = enums.DOOHVenueType_name
var DOOHVenueType_value = enums.DOOHVenueType_value

type EventTrackingMethod = enums.EventTrackingMethod

const EventTrackingMethod_EventTrackingMethod_UNKNOWN = enums.EventTrackingMethod_EventTrackingMethod_UNKNOWN
const EventTrackingMethod_IMAGE_PIXEL = enums.EventTrackingMethod_IMAGE_PIXEL
const EventTrackingMethod_JAVASCRIPT = enums.EventTrackingMethod_JAVASCRIPT

var EventTrackingMethod_name = enums.EventTrackingMethod_name
var EventTrackingMethod_value = enums.EventTrackingMethod_value

type EventType = enums.EventType

const EventType_EventType_UNKNOWN = enums.EventType_EventType_UNKNOWN
const EventType_LOADED = enums.EventType_LOADED
const EventType_IMPRESSION = enums.EventType_IMPRESSION
const EventType_VIEWABLE_MRC50 = enums.EventType_VIEWABLE_MRC50
const EventType_VIEWABLE_MRC100 = enums.EventType_VIEWABLE_MRC100
const EventType_VIEWABLE_VIDEO50 = enums.EventType_VIEWABLE_VIDEO50

var EventType_name = enums.EventType_name
var EventType_value = enums.EventType_value

type ExpandableDirection = enums.ExpandableDirection

const ExpandableDirection_ExpandableDirection_UNKNOWN = enums.ExpandableDirection_ExpandableDirection_UNKNOWN
const ExpandableDirection_LEFT = enums.ExpandableDirection_LEFT
const ExpandableDirection_RIGHT = enums.ExpandableDirection_RIGHT
const ExpandableDirection_UP = enums.ExpandableDirection_UP
const ExpandableDirection_DOWN = enums.ExpandableDirection_DOWN
const ExpandableDirection_FULLSCREEN = enums.ExpandableDirection_FULLSCREEN
const ExpandableDirection_MINIMIZE = enums.ExpandableDirection_MINIMIZE

var ExpandableDirection_name = enums.ExpandableDirection_name
var ExpandableDirection_value = enums.ExpandableDirection_value

type FeedType = enums.FeedType

const FeedType_FeedType_UNKNOWN = enums.FeedType_FeedType_UNKNOWN
const FeedType_MUSIC_SERVICE = enums.FeedType_MUSIC_SERVICE
const FeedType_FM_AM_BROADCAST = enums.FeedType_FM_AM_BROADCAST
const FeedType_PODCAST = enums.FeedType_PODCAST

var FeedType_name = enums.FeedType_name
var FeedType_value = enums.FeedType_value

type MatchMethod = enums.MatchMethod

const MatchMethod_MatchMethod_UNKNOWN = enums.MatchMethod_MatchMethod_UNKNOWN
const MatchMethod_NO_MATCH = enums.MatchMethod_NO_MATCH
const MatchMethod_BROWSER_COOKIE_SYNC = enums.MatchMethod_BROWSER_COOKIE_SYNC
const MatchMethod_AUTHENTICATED = enums.MatchMethod_AUTHENTICATED
const MatchMethod_OBSERVED = enums.MatchMethod_OBSERVED
const MatchMethod_INFERRED = enums.MatchMethod_INFERRED

var MatchMethod_name = enums.MatchMethod_name
var MatchMethod_value = enums.MatchMethod_value

type LocationService = enums.LocationService

const LocationService_LocationService_UNKNOWN = enums.LocationService_LocationService_UNKNOWN
const LocationService_IP2LOCATION = enums.LocationService_IP2LOCATION
const LocationService_NEUSTAR = enums.LocationService_NEUSTAR
const LocationService_MAXMIND = enums.LocationService_MAXMIND
const LocationService_NETACUITY = enums.LocationService_NETACUITY

var LocationService_name = enums.LocationService_name
var LocationService_value = enums.LocationService_value

type LinearityMode = enums.LinearityMode

const LinearityMode_LinearityMode_UNKNOWN = enums.LinearityMode_LinearityMode_UNKNOWN
const LinearityMode_LINEAR = enums.LinearityMode_LINEAR
const LinearityMode_NONLINEAR = enums.LinearityMode_NONLINEAR

var LinearityMode_name = enums.LinearityMode_name
var LinearityMode_value = enums.LinearityMode_value

type LocationType = enums.LocationType

const LocationType_LocationType_UNKNOWN = enums.LocationType_LocationType_UNKNOWN
const LocationType_GPS_LOC_SERVICE = enums.LocationType_GPS_LOC_SERVICE
const LocationType_IP_ADDRESS = enums.LocationType_IP_ADDRESS
const LocationType_USER_PROVIDED = enums.LocationType_USER_PROVIDED

var LocationType_name = enums.LocationType_name
var LocationType_value = enums.LocationType_value

type MediaRating = enums.MediaRating

const MediaRating_MediaRating_UNKNOWN = enums.MediaRating_MediaRating_UNKNOWN
const MediaRating_ALL_AUDIENCES = enums.MediaRating_ALL_AUDIENCES
const MediaRating_OVER_12 = enums.MediaRating_OVER_12
const MediaRating_MATURE = enums.MediaRating_MATURE

var MediaRating_name = enums.MediaRating_name
var MediaRating_value = enums.MediaRating_value

type NativeDataAssetType = enums.NativeDataAssetType

const NativeDataAssetType_NativeDataAssetType_UNKNOWN = enums.NativeDataAssetType_NativeDataAssetType_UNKNOWN
const NativeDataAssetType_SPONSORED = enums.NativeDataAssetType_SPONSORED
const NativeDataAssetType_DESCRIPTIVE = enums.NativeDataAssetType_DESCRIPTIVE
const NativeDataAssetType_RATING = enums.NativeDataAssetType_RATING
const NativeDataAssetType_LIKES = enums.NativeDataAssetType_LIKES
const NativeDataAssetType_DOWNLOADS = enums.NativeDataAssetType_DOWNLOADS
const NativeDataAssetType_PRICE = enums.NativeDataAssetType_PRICE
const NativeDataAssetType_SALEPRICE = enums.NativeDataAssetType_SALEPRICE
const NativeDataAssetType_PHONE_X = enums.NativeDataAssetType_PHONE_X
const NativeDataAssetType_ADDRESS = enums.NativeDataAssetType_ADDRESS
const NativeDataAssetType_DESC2 = enums.NativeDataAssetType_DESC2
const NativeDataAssetType_DISPLAY_URL = enums.NativeDataAssetType_DISPLAY_URL
const NativeDataAssetType_CTA_TEXT = enums.NativeDataAssetType_CTA_TEXT

var NativeDataAssetType_name = enums.NativeDataAssetType_name
var NativeDataAssetType_value = enums.NativeDataAssetType_value

type NativeImageAssetType = enums.NativeImageAssetType

const NativeImageAssetType_NativeImageAssetType_UNKNOWN = enums.NativeImageAssetType_NativeImageAssetType_UNKNOWN
const NativeImageAssetType_ICON = enums.NativeImageAssetType_ICON
const NativeImageAssetType_MAIN = enums.NativeImageAssetType_MAIN

var NativeImageAssetType_name = enums.NativeImageAssetType_name
var NativeImageAssetType_value = enums.NativeImageAssetType_value

type OperatingSystem = enums.OperatingSystem

const OperatingSystem_OTHER_NOT_LISTED = enums.OperatingSystem_OTHER_NOT_LISTED
const OperatingSystem_NINTENDO_3DS = enums.OperatingSystem_NINTENDO_3DS
const OperatingSystem_ANDROID = enums.OperatingSystem_ANDROID
const OperatingSystem_APPLE_TV = enums.OperatingSystem_APPLE_TV
const OperatingSystem_ASHA = enums.OperatingSystem_ASHA
const OperatingSystem_BADA = enums.OperatingSystem_BADA
const OperatingSystem_BLACKBERRY = enums.OperatingSystem_BLACKBERRY
const OperatingSystem_BREW = enums.OperatingSystem_BREW
const OperatingSystem_CHROMEOS = enums.OperatingSystem_CHROMEOS
const OperatingSystem_DARWIN = enums.OperatingSystem_DARWIN
const OperatingSystem_FIREOS = enums.OperatingSystem_FIREOS
const OperatingSystem_FIREFOXOS = enums.OperatingSystem_FIREFOXOS
const OperatingSystem_HELENOS = enums.OperatingSystem_HELENOS
const OperatingSystem_IOS = enums.OperatingSystem_IOS
const OperatingSystem_LINUX = enums.OperatingSystem_LINUX
const OperatingSystem_MACOS = enums.OperatingSystem_MACOS
const OperatingSystem_MEEGO = enums.OperatingSystem_MEEGO
const OperatingSystem_MORPHOS = enums.OperatingSystem_MORPHOS
const OperatingSystem_NETBSD = enums.OperatingSystem_NETBSD
const OperatingSystem_NUCLEUSPLUS = enums.OperatingSystem_NUCLEUSPLUS
const OperatingSystem_PSVITA = enums.OperatingSystem_PSVITA
const OperatingSystem_PS3 = enums.OperatingSystem_PS3
const OperatingSystem_PS4 = enums.OperatingSystem_PS4
const OperatingSystem_PSP = enums.OperatingSystem_PSP
const OperatingSystem_SYMBIAN = enums.OperatingSystem_SYMBIAN
const OperatingSystem_TIZEN = enums.OperatingSystem_TIZEN
const OperatingSystem_WATCHOS = enums.OperatingSystem_WATCHOS
const OperatingSystem_WEBOS = enums.OperatingSystem_WEBOS
const OperatingSystem_WINDOWS = enums.OperatingSystem_WINDOWS

var OperatingSystem_name = enums.OperatingSystem_name
var OperatingSystem_value = enums.OperatingSystem_value

type PlacementPosition = enums.PlacementPosition

const PlacementPosition_PlacementPosition_UNKNOWN = enums.PlacementPosition_PlacementPosition_UNKNOWN
const PlacementPosition_ATF = enums.PlacementPosition_ATF
const PlacementPosition_LOCKED = enums.PlacementPosition_LOCKED
const PlacementPosition_BTF = enums.PlacementPosition_BTF
const PlacementPosition_HEADER = enums.PlacementPosition_HEADER
const PlacementPosition_FOOTER = enums.PlacementPosition_FOOTER
const PlacementPosition_SIDEBAR = enums.PlacementPosition_SIDEBAR
const PlacementPosition_FULLSCREEN_X = enums.PlacementPosition_FULLSCREEN_X

var PlacementPosition_name = enums.PlacementPosition_name
var PlacementPosition_value = enums.PlacementPosition_value

type VideoPlacementSubtype = enums.VideoPlacementSubtype

const VideoPlacementSubtype_VideoPlacementSubtype_UNKNOWN = enums.VideoPlacementSubtype_VideoPlacementSubtype_UNKNOWN
const VideoPlacementSubtype_IN_STREAM = enums.VideoPlacementSubtype_IN_STREAM
const VideoPlacementSubtype_IN_BANNER = enums.VideoPlacementSubtype_IN_BANNER
const VideoPlacementSubtype_IN_ARTICLE = enums.VideoPlacementSubtype_IN_ARTICLE
const VideoPlacementSubtype_IN_FEED = enums.VideoPlacementSubtype_IN_FEED
const VideoPlacementSubtype_INTERSTITIAL = enums.VideoPlacementSubtype_INTERSTITIAL

var VideoPlacementSubtype_name = enums.VideoPlacementSubtype_name
var VideoPlacementSubtype_value = enums.VideoPlacementSubtype_value

type VideoPlcmtSubtype = enums.VideoPlcmtSubtype

const VideoPlcmtSubtype_VideoPlcmtSubtype_UNKNOWN = enums.VideoPlcmtSubtype_VideoPlcmtSubtype_UNKNOWN
const VideoPlcmtSubtype_INSTREAM_PLCMT = enums.VideoPlcmtSubtype_INSTREAM_PLCMT
const VideoPlcmtSubtype_ACCOMPANYING_CONTENT_PLCMT = enums.VideoPlcmtSubtype_ACCOMPANYING_CONTENT_PLCMT
const VideoPlcmtSubtype_INTERSTITIAL_PLCMT = enums.VideoPlcmtSubtype_INTERSTITIAL_PLCMT
const VideoPlcmtSubtype_STANDALONE_PLCMT = enums.VideoPlcmtSubtype_STANDALONE_PLCMT

var VideoPlcmtSubtype_name = enums.VideoPlcmtSubtype_name
var VideoPlcmtSubtype_value = enums.VideoPlcmtSubtype_value

type PlaybackCessationMode = enums.PlaybackCessationMode

const PlaybackCessationMode_PlaybackCessationMode_UNKNOWN = enums.PlaybackCessationMode_PlaybackCessationMode_UNKNOWN
const PlaybackCessationMode_ON_COMPLETION = enums.PlaybackCessationMode_ON_COMPLETION
const PlaybackCessationMode_ON_VIEWPORT_EXIT = enums.PlaybackCessationMode_ON_VIEWPORT_EXIT
const PlaybackCessationMode_ON_EXIT_FLOAT = enums.PlaybackCessationMode_ON_EXIT_FLOAT

var PlaybackCessationMode_name = enums.PlaybackCessationMode_name
var PlaybackCessationMode_value = enums.PlaybackCessationMode_value

type PlaybackMethod = enums.PlaybackMethod

const PlaybackMethod_PlaybackMethod_UNKNOWN = enums.PlaybackMethod_PlaybackMethod_UNKNOWN
const PlaybackMethod_PAGE_LOAD_SOUND_ON = enums.PlaybackMethod_PAGE_LOAD_SOUND_ON
const PlaybackMethod_PAGE_LOAD_SOUND_OFF = enums.PlaybackMethod_PAGE_LOAD_SOUND_OFF
const PlaybackMethod_CLICK_SOUND_ON = enums.PlaybackMethod_CLICK_SOUND_ON
const PlaybackMethod_MOUSEOVER_SOUND_ON = enums.PlaybackMethod_MOUSEOVER_SOUND_ON
const PlaybackMethod_VIEWPORT_SOUND_ON = enums.PlaybackMethod_VIEWPORT_SOUND_ON
const PlaybackMethod_VIEWPORT_SOUND_OFF = enums.PlaybackMethod_VIEWPORT_SOUND_OFF

var PlaybackMethod_name = enums.PlaybackMethod_name
var PlaybackMethod_value = enums.PlaybackMethod_value

type ProductionQuality = enums.ProductionQuality

const ProductionQuality_ProductionQuality_UNKNOWN = enums.ProductionQuality_ProductionQuality_UNKNOWN
const ProductionQuality_PROFESSIONAL = enums.ProductionQuality_PROFESSIONAL
const ProductionQuality_PROSUMER = enums.ProductionQuality_PROSUMER
const ProductionQuality_UGC = enums.ProductionQuality_UGC

var ProductionQuality_name = enums.ProductionQuality_name
var ProductionQuality_value = enums.ProductionQuality_value

type SizeUnit = enums.SizeUnit

const SizeUnit_SizeUnit_UNKNOWN = enums.SizeUnit_SizeUnit_UNKNOWN
const SizeUnit_DIPS = enums.SizeUnit_DIPS
const SizeUnit_INCH = enums.SizeUnit_INCH
const SizeUnit_CENTIMETER = enums.SizeUnit_CENTIMETER

var SizeUnit_name = enums.SizeUnit_name
var SizeUnit_value = enums.SizeUnit_value

type StartDelayMode = enums.StartDelayMode

const StartDelayMode_PRE_ROLL = enums.StartDelayMode_PRE_ROLL
const StartDelayMode_GENERIC_MID_ROLL = enums.StartDelayMode_GENERIC_MID_ROLL
const StartDelayMode_GENERIC_POST_ROLL = enums.StartDelayMode_GENERIC_POST_ROLL

var StartDelayMode_name = enums.StartDelayMode_name
var StartDelayMode_value = enums.StartDelayMode_value

type VolumeNormalizationMode = enums.VolumeNormalizationMode

const VolumeNormalizationMode_NO_NORMALIZATION = enums.VolumeNormalizationMode_NO_NORMALIZATION
const VolumeNormalizationMode_VOL_AVG_NORMALIZATION = enums.VolumeNormalizationMode_VOL_AVG_NORMALIZATION
const VolumeNormalizationMode_VOL_PEAK_NORMALIZATION = enums.VolumeNormalizationMode_VOL_PEAK_NORMALIZATION
const VolumeNormalizationMode_LOUDNESS_NORMALIZATION = enums.VolumeNormalizationMode_LOUDNESS_NORMALIZATION
const VolumeNormalizationMode_VOL_CUST_NORMALIZATION = enums.VolumeNormalizationMode_VOL_CUST_NORMALIZATION

var VolumeNormalizationMode_name = enums.VolumeNormalizationMode_name
var VolumeNormalizationMode_value = enums.VolumeNormalizationMode_value

type UserAgentSource = enums.UserAgentSource

const UserAgentSource_UserAgentSource_UNKNOWN = enums.UserAgentSource_UserAgentSource_UNKNOWN
const UserAgentSource_CLIENT_HINTS_LOW_ENTROPY = enums.UserAgentSource_CLIENT_HINTS_LOW_ENTROPY
const UserAgentSource_CLIENT_HINTS_HIGH_ENTROPY = enums.UserAgentSource_CLIENT_HINTS_HIGH_ENTROPY
const UserAgentSource_USER_AGENT_STRING = enums.UserAgentSource_USER_AGENT_STRING

var UserAgentSource_name = enums.UserAgentSource_name
var UserAgentSource_value = enums.UserAgentSource_value

type Creative_Attribute = enums.Creative_Attribute

const Creative_Attribute_UNKNOWN = enums.Creative_Attribute_UNKNOWN
const Creative_AUDIO_AUTOPLAY = enums.Creative_AUDIO_AUTOPLAY
const Creative_AUDIO_USER_INIT = enums.Creative_AUDIO_USER_INIT
const Creative_EXPANDABLE_AUTO = enums.Creative_EXPANDABLE_AUTO
const Creative_EXPANDABLE_ONCLICK = enums.Creative_EXPANDABLE_ONCLICK
const Creative_EXPANDABLE_ONROLLOVER = enums.Creative_EXPANDABLE_ONROLLOVER
const Creative_IB_VIDEO_AUTO = enums.Creative_IB_VIDEO_AUTO
const Creative_IB_VIDEO_USER_INIT = enums.Creative_IB_VIDEO_USER_INIT
const Creative_POP = enums.Creative_POP
const Creative_PROVOCATIVE = enums.Creative_PROVOCATIVE
const Creative_ANNOYING = enums.Creative_ANNOYING
const Creative_SURVEYS = enums.Creative_SURVEYS
const Creative_TEXT_ONLY = enums.Creative_TEXT_ONLY
const Creative_USER_INTERACTIVE = enums.Creative_USER_INTERACTIVE
const Creative_DIALOG_ALERT = enums.Creative_DIALOG_ALERT
const Creative_AUDIO_ON_OFF = enums.Creative_AUDIO_ON_OFF
const Creative_SKIP_BUTTON = enums.Creative_SKIP_BUTTON
const Creative_ADOBE_FLASH = enums.Creative_ADOBE_FLASH
const Creative_RESPONSIVE = enums.Creative_RESPONSIVE

var Creative_Attribute_name = enums.Creative_Attribute_name
var Creative_Attribute_value = enums.Creative_Attribute_value

type Creative_AudioVideoType = enums.Creative_AudioVideoType

const Creative_AudioVideoType_UNKNOWN = enums.Creative_AudioVideoType_UNKNOWN
const Creative_VAST_1_0 = enums.Creative_VAST_1_0
const Creative_VAST_2_0 = enums.Creative_VAST_2_0
const Creative_VAST_3_0 = enums.Creative_VAST_3_0
const Creative_VAST_1_0_WRAP = enums.Creative_VAST_1_0_WRAP
const Creative_VAST_2_0_WRAP = enums.Creative_VAST_2_0_WRAP
const Creative_VAST_3_0_WRAP = enums.Creative_VAST_3_0_WRAP
const Creative_VAST_4_0 = enums.Creative_VAST_4_0
const Creative_VAST_4_0_WRAP = enums.Creative_VAST_4_0_WRAP
const Creative_DAAST_1_0 = enums.Creative_DAAST_1_0
const Creative_DAAST_1_0_WRAP = enums.Creative_DAAST_1_0_WRAP
const Creative_VAST_4_1 = enums.Creative_VAST_4_1
const Creative_VAST_4_1_WRAP = enums.Creative_VAST_4_1_WRAP
const Creative_VAST_4_2 = enums.Creative_VAST_4_2
const Creative_VAST_4_2_WRAP = enums.Creative_VAST_4_2_WRAP

var Creative_AudioVideoType_name = enums.Creative_AudioVideoType_name
var Creative_AudioVideoType_value = enums.Creative_AudioVideoType_value

type Creative_DisplayType = enums.Creative_DisplayType

const Creative_DisplayType_UNKNOWN = enums.Creative_DisplayType_UNKNOWN
const Creative_HTML = enums.Creative_HTML
const Creative_AMPHTML = enums.Creative_AMPHTML
const Creative_IMAGE = enums.Creative_IMAGE
const Creative_NATIVE = enums.Creative_NATIVE

var Creative_DisplayType_name = enums.Creative_DisplayType_name
var Creative_DisplayType_value = enums.Creative_DisplayType_value

type Creative = enums.Creative

// Symbols defined in public import of com/iabtechlab/adcom/v1/context/context.proto.

type DistributionChannel = context.DistributionChannel
type DistributionChannel_Site_ = context.DistributionChannel_Site_
type DistributionChannel_App_ = context.DistributionChannel_App_
type DistributionChannel_Dooh = context.DistributionChannel_Dooh
type Publisher = context.Publisher
type Content = context.Content
type Producer = context.Producer
type UniversalId = context.UniversalId
type ExtendedId = context.ExtendedId
type User = context.User
type Device = context.Device
type Geo = context.Geo
type Data = context.Data
type Segment = context.Segment
type Regs = context.Regs
type Restrictions = context.Restrictions
type DistributionChannel_Site = context.DistributionChannel_Site
type DistributionChannel_App = context.DistributionChannel_App
type DistributionChannel_DOOH = context.DistributionChannel_DOOH

// Symbols defined in public import of com/iabtechlab/adcom/v1/media/media.proto.

type Ad = media.Ad

const Default_Ad_Cattax = media.Default_Ad_Cattax

type Ad_Display_ = media.Ad_Display_
type Ad_Video_ = media.Ad_Video_
type Ad_Audio_ = media.Ad_Audio_
type Ad_Display = media.Ad_Display
type Ad_Display_Adm = media.Ad_Display_Adm
type Ad_Display_Curl = media.Ad_Display_Curl
type Ad_Display_Banner_ = media.Ad_Display_Banner_
type Ad_Display_Native_ = media.Ad_Display_Native_
type Ad_Video = media.Ad_Video
type Ad_Video_Adm = media.Ad_Video_Adm
type Ad_Video_Curl = media.Ad_Video_Curl
type Ad_Audio = media.Ad_Audio
type Ad_Audio_Adm = media.Ad_Audio_Adm
type Ad_Audio_Curl = media.Ad_Audio_Curl
type Ad_Audit = media.Ad_Audit
type Ad_Display_Banner = media.Ad_Display_Banner
type Ad_Display_Native = media.Ad_Display_Native
type Ad_Display_Event = media.Ad_Display_Event
type Ad_Display_Native_Asset = media.Ad_Display_Native_Asset
type Ad_Display_Native_Asset_Title = media.Ad_Display_Native_Asset_Title
type Ad_Display_Native_Asset_Image = media.Ad_Display_Native_Asset_Image
type Ad_Display_Native_Asset_Video = media.Ad_Display_Native_Asset_Video
type Ad_Display_Native_Asset_Data = media.Ad_Display_Native_Asset_Data
type Ad_Display_Native_Asset_Link = media.Ad_Display_Native_Asset_Link
type Ad_Display_Native_Asset_LinkAsset = media.Ad_Display_Native_Asset_LinkAsset
type Ad_Display_Native_Asset_TitleAsset = media.Ad_Display_Native_Asset_TitleAsset
type Ad_Display_Native_Asset_ImageAsset = media.Ad_Display_Native_Asset_ImageAsset
type Ad_Display_Native_Asset_VideoAsset = media.Ad_Display_Native_Asset_VideoAsset
type Ad_Display_Native_Asset_VideoAsset_Adm = media.Ad_Display_Native_Asset_VideoAsset_Adm
type Ad_Display_Native_Asset_VideoAsset_Curl = media.Ad_Display_Native_Asset_VideoAsset_Curl
type Ad_Display_Native_Asset_DataAsset = media.Ad_Display_Native_Asset_DataAsset

// Symbols defined in public import of com/iabtechlab/adcom/v1/placement/placement.proto.

type Placement = placement.Placement
type Placement_DisplayPlacement = placement.Placement_DisplayPlacement

const Default_Placement_DisplayPlacement_Unit = placement.Default_Placement_DisplayPlacement_Unit

type Placement_VideoPlacement = placement.Placement_VideoPlacement

const Default_Placement_VideoPlacement_Unit = placement.Default_Placement_VideoPlacement_Unit
const Default_Placement_VideoPlacement_Boxing = placement.Default_Placement_VideoPlacement_Boxing

type Placement_AudioPlacement = placement.Placement_AudioPlacement
type Placement_Companion = placement.Placement_Companion
type Placement_DisplayPlacement_DisplayFormat = placement.Placement_DisplayPlacement_DisplayFormat
type Placement_DisplayPlacement_NativeFormat = placement.Placement_DisplayPlacement_NativeFormat
type Placement_DisplayPlacement_EventSpec = placement.Placement_DisplayPlacement_EventSpec

const Default_Placement_DisplayPlacement_EventSpec_Wjs = placement.Default_Placement_DisplayPlacement_EventSpec_Wjs
const Default_Placement_DisplayPlacement_EventSpec_Wpx = placement.Default_Placement_DisplayPlacement_EventSpec_Wpx

type Placement_DisplayPlacement_NativeFormat_AssetFormat = placement.Placement_DisplayPlacement_NativeFormat_AssetFormat
type Placement_DisplayPlacement_NativeFormat_AssetFormat_Title = placement.Placement_DisplayPlacement_NativeFormat_AssetFormat_Title
type Placement_DisplayPlacement_NativeFormat_AssetFormat_Img = placement.Placement_DisplayPlacement_NativeFormat_AssetFormat_Img
type Placement_DisplayPlacement_NativeFormat_AssetFormat_Video = placement.Placement_DisplayPlacement_NativeFormat_AssetFormat_Video
type Placement_DisplayPlacement_NativeFormat_AssetFormat_Data = placement.Placement_DisplayPlacement_NativeFormat_AssetFormat_Data
type Placement_DisplayPlacement_NativeFormat_AssetFormat_TitleAssetFormat = placement.Placement_DisplayPlacement_NativeFormat_AssetFormat_TitleAssetFormat
type Placement_DisplayPlacement_NativeFormat_AssetFormat_ImageAssetFormat = placement.Placement_DisplayPlacement_NativeFormat_AssetFormat_ImageAssetFormat
type Placement_DisplayPlacement_NativeFormat_AssetFormat_DataAssetFormat = placement.Placement_DisplayPlacement_NativeFormat_AssetFormat_DataAssetFormat

var File_com_iabtechlab_adcom_v1_adcom_proto protoreflect.FileDescriptor

var file_com_iabtechlab_adcom_v1_adcom_proto_rawDesc = []byte{
	0x0a, 0x23, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x61, 0x62, 0x74, 0x65, 0x63, 0x68, 0x6c, 0x61, 0x62,
	0x2f, 0x61, 0x64, 0x63, 0x6f, 0x6d, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x64, 0x63, 0x6f, 0x6d, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x63, 0x6f, 0x6d, 0x2e, 0x69, 0x61, 0x62, 0x74, 0x65,
	0x63, 0x68, 0x6c, 0x61, 0x62, 0x2e, 0x61, 0x64, 0x63, 0x6f, 0x6d, 0x2e, 0x76, 0x31, 0x1a, 0x29,
	0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x61, 0x62, 0x74, 0x65, 0x63, 0x68, 0x6c, 0x61, 0x62, 0x2f, 0x61,
	0x64, 0x63, 0x6f, 0x6d, 0x2f, 0x76, 0x31, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x2f, 0x65, 0x6e,
	0x75, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x2d, 0x63, 0x6f, 0x6d, 0x2f, 0x69,
	0x61, 0x62, 0x74, 0x65, 0x63, 0x68, 0x6c, 0x61, 0x62, 0x2f, 0x61, 0x64, 0x63, 0x6f, 0x6d, 0x2f,
	0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x78, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x29, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x61,
	0x62, 0x74, 0x65, 0x63, 0x68, 0x6c, 0x61, 0x62, 0x2f, 0x61, 0x64, 0x63, 0x6f, 0x6d, 0x2f, 0x76,
	0x31, 0x2f, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2f, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x31, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x61, 0x62, 0x74, 0x65, 0x63, 0x68,
	0x6c, 0x61, 0x62, 0x2f, 0x61, 0x64, 0x63, 0x6f, 0x6d, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x6c, 0x61,
	0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2f, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x42, 0xf5, 0x01, 0x0a, 0x1b, 0x63, 0x6f, 0x6d, 0x2e, 0x63,
	0x6f, 0x6d, 0x2e, 0x69, 0x61, 0x62, 0x74, 0x65, 0x63, 0x68, 0x6c, 0x61, 0x62, 0x2e, 0x61, 0x64,
	0x63, 0x6f, 0x6d, 0x2e, 0x76, 0x31, 0x42, 0x0a, 0x41, 0x64, 0x63, 0x6f, 0x6d, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x50, 0x01, 0x5a, 0x4b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x62, 0x69, 0x64, 0x6f, 0x6e, 0x2d, 0x69, 0x6f, 0x2f, 0x62, 0x69, 0x64, 0x6f, 0x6e, 0x2d,
	0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x61, 0x62, 0x74, 0x65, 0x63, 0x68, 0x6c, 0x61, 0x62,
	0x2f, 0x61, 0x64, 0x63, 0x6f, 0x6d, 0x2f, 0x76, 0x31, 0x3b, 0x61, 0x64, 0x63, 0x6f, 0x6d, 0x76,
	0x31, 0xa2, 0x02, 0x03, 0x43, 0x49, 0x41, 0xaa, 0x02, 0x17, 0x43, 0x6f, 0x6d, 0x2e, 0x49, 0x61,
	0x62, 0x74, 0x65, 0x63, 0x68, 0x6c, 0x61, 0x62, 0x2e, 0x41, 0x64, 0x63, 0x6f, 0x6d, 0x2e, 0x56,
	0x31, 0xca, 0x02, 0x17, 0x43, 0x6f, 0x6d, 0x5c, 0x49, 0x61, 0x62, 0x74, 0x65, 0x63, 0x68, 0x6c,
	0x61, 0x62, 0x5c, 0x41, 0x64, 0x63, 0x6f, 0x6d, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x23, 0x43, 0x6f,
	0x6d, 0x5c, 0x49, 0x61, 0x62, 0x74, 0x65, 0x63, 0x68, 0x6c, 0x61, 0x62, 0x5c, 0x41, 0x64, 0x63,
	0x6f, 0x6d, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0xea, 0x02, 0x1a, 0x43, 0x6f, 0x6d, 0x3a, 0x3a, 0x49, 0x61, 0x62, 0x74, 0x65, 0x63, 0x68,
	0x6c, 0x61, 0x62, 0x3a, 0x3a, 0x41, 0x64, 0x63, 0x6f, 0x6d, 0x3a, 0x3a, 0x56, 0x31, 0x50, 0x00,
	0x50, 0x01, 0x50, 0x02, 0x50, 0x03,
}

var file_com_iabtechlab_adcom_v1_adcom_proto_goTypes = []any{}
var file_com_iabtechlab_adcom_v1_adcom_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_com_iabtechlab_adcom_v1_adcom_proto_init() }
func file_com_iabtechlab_adcom_v1_adcom_proto_init() {
	if File_com_iabtechlab_adcom_v1_adcom_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_com_iabtechlab_adcom_v1_adcom_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_com_iabtechlab_adcom_v1_adcom_proto_goTypes,
		DependencyIndexes: file_com_iabtechlab_adcom_v1_adcom_proto_depIdxs,
	}.Build()
	File_com_iabtechlab_adcom_v1_adcom_proto = out.File
	file_com_iabtechlab_adcom_v1_adcom_proto_rawDesc = nil
	file_com_iabtechlab_adcom_v1_adcom_proto_goTypes = nil
	file_com_iabtechlab_adcom_v1_adcom_proto_depIdxs = nil
}
