-- +goose Up
-- +goose StatementBegin
INSERT INTO countries (alpha_2_code, alpha_3_code, human_name, created_at, updated_at)
VALUES
-- Africa (54 countries)
('DZ', 'DZA', 'Algeria', NOW(), NOW()),
('AO', 'AGO', 'Angola', NOW(), NOW()),
('BJ', 'BEN', 'Benin', NOW(), NOW()),
('BW', 'BWA', 'Botswana', NOW(), NOW()),
('BF', 'BFA', 'Burkina Faso', NOW(), NOW()),
('BI', 'BDI', 'Burundi', NOW(), NOW()),
('CM', 'CMR', 'Cameroon', NOW(), NOW()),
('CV', 'CPV', 'Cape Verde', NOW(), NOW()),
('CF', 'CAF', 'Central African Republic', NOW(), NOW()),
('TD', 'TCD', 'Chad', NOW(), NOW()),
('KM', 'COM', 'Comoros', NOW(), NOW()),
('CG', 'COG', 'Congo', NOW(), NOW()),
('CD', 'COD', 'Democratic Republic of the Congo', NOW(), NOW()),
('DJ', 'DJI', 'Djibouti', NOW(), NOW()),
('EG', 'EGY', 'Egypt', NOW(), NOW()),
('GQ', 'GNQ', 'Equatorial Guinea', NOW(), NOW()),
('ER', 'ERI', 'Eritrea', NOW(), NOW()),
('SZ', 'SWZ', 'Eswatini', NOW(), NOW()),
('ET', 'ETH', 'Ethiopia', NOW(), NOW()),
('GA', 'GAB', 'Gabon', NOW(), NOW()),
('GM', 'GMB', 'Gambia', NOW(), NOW()),
('GH', 'GHA', 'Ghana', NOW(), NOW()),
('GN', 'GIN', 'Guinea', NOW(), NOW()),
('GW', 'GNB', 'Guinea-Bissau', NOW(), NOW()),
('CI', 'CIV', 'Ivory Coast', NOW(), NOW()),
('KE', 'KEN', 'Kenya', NOW(), NOW()),
('LS', 'LSO', 'Lesotho', NOW(), NOW()),
('LR', 'LBR', 'Liberia', NOW(), NOW()),
('LY', 'LBY', 'Libya', NOW(), NOW()),
('MG', 'MDG', 'Madagascar', NOW(), NOW()),
('MW', 'MWI', 'Malawi', NOW(), NOW()),
('ML', 'MLI', 'Mali', NOW(), NOW()),
('MR', 'MRT', 'Mauritania', NOW(), NOW()),
('MU', 'MUS', 'Mauritius', NOW(), NOW()),
('MA', 'MAR', 'Morocco', NOW(), NOW()),
('MZ', 'MOZ', 'Mozambique', NOW(), NOW()),
('NA', 'NAM', 'Namibia', NOW(), NOW()),
('NE', 'NER', 'Niger', NOW(), NOW()),
('NG', 'NGA', 'Nigeria', NOW(), NOW()),
('RW', 'RWA', 'Rwanda', NOW(), NOW()),
('ST', 'STP', 'São Tomé and Príncipe', NOW(), NOW()),
('SN', 'SEN', 'Senegal', NOW(), NOW()),
('SC', 'SYC', 'Seychelles', NOW(), NOW()),
('SL', 'SLE', 'Sierra Leone', NOW(), NOW()),
('SO', 'SOM', 'Somalia', NOW(), NOW()),
('ZA', 'ZAF', 'South Africa', NOW(), NOW()),
('SS', 'SSD', 'South Sudan', NOW(), NOW()),
('SD', 'SDN', 'Sudan', NOW(), NOW()),
('TZ', 'TZA', 'Tanzania', NOW(), NOW()),
('TG', 'TGO', 'Togo', NOW(), NOW()),
('TN', 'TUN', 'Tunisia', NOW(), NOW()),
('UG', 'UGA', 'Uganda', NOW(), NOW()),
('ZM', 'ZMB', 'Zambia', NOW(), NOW()),
('ZW', 'ZWE', 'Zimbabwe', NOW(), NOW()),

-- Americas (35 countries)
('AG', 'ATG', 'Antigua and Barbuda', NOW(), NOW()),
('AR', 'ARG', 'Argentina', NOW(), NOW()),
('BS', 'BHS', 'Bahamas', NOW(), NOW()),
('BB', 'BRB', 'Barbados', NOW(), NOW()),
('BZ', 'BLZ', 'Belize', NOW(), NOW()),
('BO', 'BOL', 'Bolivia', NOW(), NOW()),
('BR', 'BRA', 'Brazil', NOW(), NOW()),
('CA', 'CAN', 'Canada', NOW(), NOW()),
('CL', 'CHL', 'Chile', NOW(), NOW()),
('CO', 'COL', 'Colombia', NOW(), NOW()),
('CR', 'CRI', 'Costa Rica', NOW(), NOW()),
('CU', 'CUB', 'Cuba', NOW(), NOW()),
('DM', 'DMA', 'Dominica', NOW(), NOW()),
('DO', 'DOM', 'Dominican Republic', NOW(), NOW()),
('EC', 'ECU', 'Ecuador', NOW(), NOW()),
('SV', 'SLV', 'El Salvador', NOW(), NOW()),
('GD', 'GRD', 'Grenada', NOW(), NOW()),
('GT', 'GTM', 'Guatemala', NOW(), NOW()),
('GY', 'GUY', 'Guyana', NOW(), NOW()),
('HT', 'HTI', 'Haiti', NOW(), NOW()),
('HN', 'HND', 'Honduras', NOW(), NOW()),
('JM', 'JAM', 'Jamaica', NOW(), NOW()),
('MX', 'MEX', 'Mexico', NOW(), NOW()),
('NI', 'NIC', 'Nicaragua', NOW(), NOW()),
('PA', 'PAN', 'Panama', NOW(), NOW()),
('PY', 'PRY', 'Paraguay', NOW(), NOW()),
('PE', 'PER', 'Peru', NOW(), NOW()),
('KN', 'KNA', 'Saint Kitts and Nevis', NOW(), NOW()),
('LC', 'LCA', 'Saint Lucia', NOW(), NOW()),
('VC', 'VCT', 'Saint Vincent and the Grenadines', NOW(), NOW()),
('SR', 'SUR', 'Suriname', NOW(), NOW()),
('TT', 'TTO', 'Trinidad and Tobago', NOW(), NOW()),
('US', 'USA', 'United States', NOW(), NOW()),
('UY', 'URY', 'Uruguay', NOW(), NOW()),
('VE', 'VEN', 'Venezuela', NOW(), NOW()),

-- Asia (49 countries)
('AF', 'AFG', 'Afghanistan', NOW(), NOW()),
('AM', 'ARM', 'Armenia', NOW(), NOW()),
('AZ', 'AZE', 'Azerbaijan', NOW(), NOW()),
('BH', 'BHR', 'Bahrain', NOW(), NOW()),
('BD', 'BGD', 'Bangladesh', NOW(), NOW()),
('BT', 'BTN', 'Bhutan', NOW(), NOW()),
('BN', 'BRN', 'Brunei', NOW(), NOW()),
('KH', 'KHM', 'Cambodia', NOW(), NOW()),
('CN', 'CHN', 'China', NOW(), NOW()),
('CY', 'CYP', 'Cyprus', NOW(), NOW()),
('GE', 'GEO', 'Georgia', NOW(), NOW()),
('IN', 'IND', 'India', NOW(), NOW()),
('ID', 'IDN', 'Indonesia', NOW(), NOW()),
('IR', 'IRN', 'Iran', NOW(), NOW()),
('IQ', 'IRQ', 'Iraq', NOW(), NOW()),
('IL', 'ISR', 'Israel', NOW(), NOW()),
('JP', 'JPN', 'Japan', NOW(), NOW()),
('JO', 'JOR', 'Jordan', NOW(), NOW()),
('KZ', 'KAZ', 'Kazakhstan', NOW(), NOW()),
('KW', 'KWT', 'Kuwait', NOW(), NOW()),
('KG', 'KGZ', 'Kyrgyzstan', NOW(), NOW()),
('LA', 'LAO', 'Laos', NOW(), NOW()),
('LB', 'LBN', 'Lebanon', NOW(), NOW()),
('MY', 'MYS', 'Malaysia', NOW(), NOW()),
('MV', 'MDV', 'Maldives', NOW(), NOW()),
('MN', 'MNG', 'Mongolia', NOW(), NOW()),
('MM', 'MMR', 'Myanmar', NOW(), NOW()),
('NP', 'NPL', 'Nepal', NOW(), NOW()),
('KP', 'PRK', 'North Korea', NOW(), NOW()),
('OM', 'OMN', 'Oman', NOW(), NOW()),
('PK', 'PAK', 'Pakistan', NOW(), NOW()),
('PS', 'PSE', 'Palestine', NOW(), NOW()),
('PH', 'PHL', 'Philippines', NOW(), NOW()),
('QA', 'QAT', 'Qatar', NOW(), NOW()),
('SA', 'SAU', 'Saudi Arabia', NOW(), NOW()),
('SG', 'SGP', 'Singapore', NOW(), NOW()),
('KR', 'KOR', 'South Korea', NOW(), NOW()),
('LK', 'LKA', 'Sri Lanka', NOW(), NOW()),
('SY', 'SYR', 'Syria', NOW(), NOW()),
('TW', 'TWN', 'Taiwan', NOW(), NOW()),
('TJ', 'TJK', 'Tajikistan', NOW(), NOW()),
('TH', 'THA', 'Thailand', NOW(), NOW()),
('TL', 'TLS', 'Timor-Leste', NOW(), NOW()),
('TR', 'TUR', 'Turkey', NOW(), NOW()),
('TM', 'TKM', 'Turkmenistan', NOW(), NOW()),
('AE', 'ARE', 'United Arab Emirates', NOW(), NOW()),
('UZ', 'UZB', 'Uzbekistan', NOW(), NOW()),
('VN', 'VNM', 'Vietnam', NOW(), NOW()),
('YE', 'YEM', 'Yemen', NOW(), NOW()),

-- Europe (44 countries)
('AL', 'ALB', 'Albania', NOW(), NOW()),
('AD', 'AND', 'Andorra', NOW(), NOW()),
('AT', 'AUT', 'Austria', NOW(), NOW()),
('BY', 'BLR', 'Belarus', NOW(), NOW()),
('BE', 'BEL', 'Belgium', NOW(), NOW()),
('BA', 'BIH', 'Bosnia and Herzegovina', NOW(), NOW()),
('BG', 'BGR', 'Bulgaria', NOW(), NOW()),
('HR', 'HRV', 'Croatia', NOW(), NOW()),
('CZ', 'CZE', 'Czech Republic', NOW(), NOW()),
('DK', 'DNK', 'Denmark', NOW(), NOW()),
('EE', 'EST', 'Estonia', NOW(), NOW()),
('FI', 'FIN', 'Finland', NOW(), NOW()),
('FR', 'FRA', 'France', NOW(), NOW()),
('DE', 'DEU', 'Germany', NOW(), NOW()),
('GR', 'GRC', 'Greece', NOW(), NOW()),
('HU', 'HUN', 'Hungary', NOW(), NOW()),
('IS', 'ISL', 'Iceland', NOW(), NOW()),
('IE', 'IRL', 'Ireland', NOW(), NOW()),
('IT', 'ITA', 'Italy', NOW(), NOW()),
('LV', 'LVA', 'Latvia', NOW(), NOW()),
('LI', 'LIE', 'Liechtenstein', NOW(), NOW()),
('LT', 'LTU', 'Lithuania', NOW(), NOW()),
('LU', 'LUX', 'Luxembourg', NOW(), NOW()),
('MT', 'MLT', 'Malta', NOW(), NOW()),
('MD', 'MDA', 'Moldova', NOW(), NOW()),
('MC', 'MCO', 'Monaco', NOW(), NOW()),
('ME', 'MNE', 'Montenegro', NOW(), NOW()),
('NL', 'NLD', 'Netherlands', NOW(), NOW()),
('MK', 'MKD', 'North Macedonia', NOW(), NOW()),
('NO', 'NOR', 'Norway', NOW(), NOW()),
('PL', 'POL', 'Poland', NOW(), NOW()),
('PT', 'PRT', 'Portugal', NOW(), NOW()),
('RO', 'ROU', 'Romania', NOW(), NOW()),
('RU', 'RUS', 'Russia', NOW(), NOW()),
('SM', 'SMR', 'San Marino', NOW(), NOW()),
('RS', 'SRB', 'Serbia', NOW(), NOW()),
('SK', 'SVK', 'Slovakia', NOW(), NOW()),
('SI', 'SVN', 'Slovenia', NOW(), NOW()),
('ES', 'ESP', 'Spain', NOW(), NOW()),
('SE', 'SWE', 'Sweden', NOW(), NOW()),
('CH', 'CHE', 'Switzerland', NOW(), NOW()),
('UA', 'UKR', 'Ukraine', NOW(), NOW()),
('GB', 'GBR', 'United Kingdom', NOW(), NOW()),
('VA', 'VAT', 'Vatican City', NOW(), NOW()),

-- Oceania (14 countries)
('AU', 'AUS', 'Australia', NOW(), NOW()),
('FJ', 'FJI', 'Fiji', NOW(), NOW()),
('KI', 'KIR', 'Kiribati', NOW(), NOW()),
('MH', 'MHL', 'Marshall Islands', NOW(), NOW()),
('FM', 'FSM', 'Micronesia', NOW(), NOW()),
('NR', 'NRU', 'Nauru', NOW(), NOW()),
('NZ', 'NZL', 'New Zealand', NOW(), NOW()),
('PW', 'PLW', 'Palau', NOW(), NOW()),
('PG', 'PNG', 'Papua New Guinea', NOW(), NOW()),
('WS', 'WSM', 'Samoa', NOW(), NOW()),
('SB', 'SLB', 'Solomon Islands', NOW(), NOW()),
('TO', 'TON', 'Tonga', NOW(), NOW()),
('TV', 'TUV', 'Tuvalu', NOW(), NOW()),
('VU', 'VUT', 'Vanuatu', NOW(), NOW())
ON CONFLICT (alpha_2_code) DO NOTHING;
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
-- +goose StatementEnd
