source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.1.2'

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem 'lograge'
gem 'pg', '~> 1.1'
gem 'puma', '~> 5.0'
gem 'rails', '~> 7.0.3', '>= 7.0.3.1'

gem 'bootsnap', require: false
gem 'json_schemer'
gem 'memo_wise'
gem 'oj'
gem 'redis'
gem 'ruby-kafka'
gem 'sequel-rails'

gem 'sentry-rails'
gem 'sentry-ruby'

group :development do
  gem 'benchmark-ips'

  gem 'rubocop', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec', require: false
end

group :development, :test do
  gem 'factory_bot_rails'
  gem 'rspec-rails'
end
