// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/bidon-io/bidon-backend/internal/adapter"
	"github.com/bidon-io/bidon-backend/internal/bidding/adapters_builder"
	"sync"
)

// Ensure, that ConfigurationFetcherMock does implement adapters_builder.ConfigurationFetcher.
// If this is not the case, regenerate this file with moq.
var _ adapters_builder.ConfigurationFetcher = &ConfigurationFetcherMock{}

// ConfigurationFetcherMock is a mock implementation of adapters_builder.ConfigurationFetcher.
//
//	func TestSomethingThatUsesConfigurationFetcher(t *testing.T) {
//
//		// make and configure a mocked adapters_builder.ConfigurationFetcher
//		mockedConfigurationFetcher := &ConfigurationFetcherMock{
//			FetchFunc: func(ctx context.Context, appID int64, adapterKeys []adapter.Key) (adapter.RawConfigsMap, error) {
//				panic("mock out the Fetch method")
//			},
//		}
//
//		// use mockedConfigurationFetcher in code that requires adapters_builder.ConfigurationFetcher
//		// and then make assertions.
//
//	}
type ConfigurationFetcherMock struct {
	// FetchFunc mocks the Fetch method.
	FetchFunc func(ctx context.Context, appID int64, adapterKeys []adapter.Key) (adapter.RawConfigsMap, error)

	// calls tracks calls to the methods.
	calls struct {
		// Fetch holds details about calls to the Fetch method.
		Fetch []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AppID is the appID argument value.
			AppID int64
			// AdapterKeys is the adapterKeys argument value.
			AdapterKeys []adapter.Key
		}
	}
	lockFetch sync.RWMutex
}

// Fetch calls FetchFunc.
func (mock *ConfigurationFetcherMock) Fetch(ctx context.Context, appID int64, adapterKeys []adapter.Key) (adapter.RawConfigsMap, error) {
	if mock.FetchFunc == nil {
		panic("ConfigurationFetcherMock.FetchFunc: method is nil but ConfigurationFetcher.Fetch was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		AppID       int64
		AdapterKeys []adapter.Key
	}{
		Ctx:         ctx,
		AppID:       appID,
		AdapterKeys: adapterKeys,
	}
	mock.lockFetch.Lock()
	mock.calls.Fetch = append(mock.calls.Fetch, callInfo)
	mock.lockFetch.Unlock()
	return mock.FetchFunc(ctx, appID, adapterKeys)
}

// FetchCalls gets all the calls that were made to Fetch.
// Check the length with:
//
//	len(mockedConfigurationFetcher.FetchCalls())
func (mock *ConfigurationFetcherMock) FetchCalls() []struct {
	Ctx         context.Context
	AppID       int64
	AdapterKeys []adapter.Key
} {
	var calls []struct {
		Ctx         context.Context
		AppID       int64
		AdapterKeys []adapter.Key
	}
	mock.lockFetch.RLock()
	calls = mock.calls.Fetch
	mock.lockFetch.RUnlock()
	return calls
}
