// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"

	"gorm.io/datatypes"
	"gorm.io/gorm"
)

const TableNameDemandSourceAccount = "demand_source_accounts"

// DemandSourceAccount mapped from table <demand_source_accounts>
type DemandSourceAccount struct {
	ID             int64          `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	DemandSourceID int64          `gorm:"column:demand_source_id;type:bigint;not null;index:index_demand_source_accounts_on_demand_source_id,priority:1" json:"demand_source_id"`
	UserID         int64          `gorm:"column:user_id;type:bigint" json:"user_id"`
	Type           string         `gorm:"column:type;type:character varying;not null" json:"type"`
	Extra          datatypes.JSON `gorm:"column:extra;type:jsonb;default:{}" json:"extra"`
	IsBidding      sql.NullBool   `gorm:"column:bidding;type:boolean;default:false" json:"bidding"`
	IsDefault      sql.NullBool   `gorm:"column:is_default;type:boolean" json:"is_default"`
	CreatedAt      time.Time      `gorm:"column:created_at;type:timestamp(6) without time zone;not null" json:"created_at"`
	UpdatedAt      time.Time      `gorm:"column:updated_at;type:timestamp(6) without time zone;not null" json:"updated_at"`
	Label          sql.NullString `gorm:"column:label;type:character varying" json:"label"`
	PublicUID      sql.NullInt64  `gorm:"column:public_uid;type:bigint;uniqueIndex:index_demand_source_accounts_on_public_uid,priority:1" json:"public_uid"`
	DeletedAt      gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp(6) without time zone" json:"deleted_at"`
	DemandSource   DemandSource   `json:"demand_source"`
	User           User           `json:"user"`
}

// TableName DemandSourceAccount's table name
func (*DemandSourceAccount) TableName() string {
	return TableNameDemandSourceAccount
}
