name: Deploy back
on:
  push:
    branches:
      - 'main'
    paths:
      - 'bidon_back/**'

jobs:
  build-and-debloy:
    runs-on: [self-hosted]
    steps:
      - name: Login registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_ADDRESS }}
          username: ${{ secrets.REGISTRY_USERNAME_DEPLOY }}
          password: ${{ secrets.REGISTRY_PASSWORD_DEPLOY }}

      - name: Checks-out repository
        uses: actions/checkout@v3

      - name: Build image
        run: make docker-build-prod-back TAG=${{ github.sha }}

      - name: Push image
        run: make docker-push-prod-back TAG=${{ github.sha }}

      - name: Checks-out repository devops
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.ANSIBLE_SECRET }}/devops
          token: ${{ secrets.PAT_RUNNER }}

      - name: Deploy
        working-directory: ./${{ secrets.ANSIBLE_SECRET }}/prod
        run: make bidon-backend TAG=${{ github.sha }}
