name: Build and Deploy Prod

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build and push nightly images
    uses: ./.github/workflows/prod-build.yml
    secrets: inherit
    with:
      tag: nightly

  deploy:
    name: Deploy prod
    needs: build
    uses: ./.github/workflows/prod-deploy.yml
    secrets: inherit
    with:
      tag: nightly

