name: Prod Deploy

on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true
        default: latest
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: true
        default: latest

jobs:
  deploy:
    name: Deploy
    runs-on: [self-hosted]
    environment: production
    env:
      TAG: ${{ inputs.tag }}
    steps:
      - name: Get latest release
        if: ${{ inputs.tag == 'latest' }}
        id: latest-release
        uses: octokit/request-action@v2
        with:
          route: GET /repos/${{ github.repository }}/releases/latest
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_RUNNER }}

      - name: Set TAG
        if: ${{ inputs.tag == 'latest' }}
        run: echo "TAG=${{ fromJson(steps.latest-release.outputs.data).tag_name }}" >> $GITHUB_ENV

      - name: Checks-out repository devops
        uses: actions/checkout@v4
        with:
          repository: bidon-io/devops
          ref: master
          token: ${{ secrets.PAT_RUNNER }}

      - name: Deploy bidon-admin
        working-directory: ./prod
        run: ANSIBLE_VAULT_PASSWORD_FILE=$ANSIBLE_VAULT_PASSWORD_FILE_BIDON && make k8s-dfw-bidon-admin TAG=$TAG

      - name: Deploy bidon-sdkapi
        working-directory: ./prod
        run: ANSIBLE_VAULT_PASSWORD_FILE=$ANSIBLE_VAULT_PASSWORD_FILE_BIDON && make k8s-dfw-bidon-sdkapi TAG=$TAG
