name: Release Nightly

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate release tag
        id: tag
        run: |
          YEAR=$(date +'%y')
          MONTH=$(date +'%-m')
          SHORT_SHA=$(git rev-parse --short HEAD)
          RELEASE_TAG="v${YEAR}.${MONTH}.nightly+${SHORT_SHA}"
          echo "RELEASE_TAG=${RELEASE_TAG}" >> $GITHUB_ENV

      - name: Create release
        run: |
          gh release create ${{ env.RELEASE_TAG }} \
            --generate-notes \
            --fail-on-no-commits \
            --latest=false \
            --prerelease
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
