name: Rspec tests

on:
  pull_request:

env:
  COMPOSE_PROJECT_NAME: pr_${{github.run_number}}
  BIDON_BACKEND_VERS: pr_${{github.run_number}}
  MAXMIND_ACCOUNT_ID: ${{ secrets.MAXMIND_GEOIPUPDATE_ACCOUNT_ID }}
  MAXMIND_LICENSE_KEY: ${{ secrets.MAXMIND_GEOIPUPDATE_LICENSE_KEY }}

jobs:
  build-back:
    name: Build backend image
    runs-on: [self-hosted]
    steps:
      - name: Checks-out repository
        uses: actions/checkout@v3

      - name: Build
        working-directory: bidon_back
        run: docker build --target=prod -t ghcr.io/bidon-io/bidon-back:$COMPOSE_PROJECT_NAME .

  start-docker-compose:
    name: Start docker compose
    runs-on: [self-hosted]
    needs: [build-back]
    steps:
      - name: Checks-out repository
        uses: actions/checkout@v3

      - name: Start docker compose
        run: |
          mkdir -m 777 test
          docker compose -f docker-compose-test.yml up -d

      - name: Start tests
        run: docker compose -f docker-compose-test.yml exec bidon-backend bundle exec rspec

      - name: Publish tests results
        if: always()
        uses: mikepenz/action-junit-report@v3
        with:
          check_name: Tests report
          report_paths: 'test/*.xml'

      - name: Start docker compose
        if: always()
        run: docker compose -f docker-compose-test.yml down -v
