name: Rust build and test

on:
  push:
    paths:
      - "proxy/**"
      - "proto/**"
      - "Cargo.toml"
      - "build.rs"
      - "Cargo.lock"
  pull_request:
    branches: [ "main" ]
    paths:
      - "proxy/**"
      - "proto/**"
      - "Cargo.toml"
      - "build.rs"
      - "Cargo.lock"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install protoc
      run: sudo apt-get install -y protobuf-compiler
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
